Repository openshift/oadp-operator, pull requests merged in 2021-12, with the labels that each got.

#486 Disconnected fix and CSV updates
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  deploy/disconnected-prep.sh
Labels: lgtm

#487 [e2e] 4.9 mongodb image parks-app fix
  tests/e2e/sample-applications/parks-app/manifest4.8.yaml
Labels: testing

#489 Update screen captures for OLM install
  docs/images/OADP-OLM-2.png
  docs/images/OADP-OLM-3.png
  docs/images/Velero-CR-1.png
  docs/images/Velero-CR-2.png
  docs/images/click-install-again.png
  docs/images/click-install.png
  docs/images/create-dpa-cr-yaml.png
  docs/images/dpa-cr.png
  docs/install_olm.md
Labels: documentation

#510 Ensure velero is deleted before proxy test starts.
  tests/e2e/subscription_suite_test.go
Labels: lgtm

#519 Updating azure credentials documentation
  docs/config/azure_plugin.md
Labels: do-not-merge/hold
