Repository openshift/oadp-operator, pull requests merged in 2021-08, with the labels that each got.

#151 Updated Restic e2e tests & added default plugins e2e tests
  tests/e2e/common.go
  tests/e2e/install.go
  tests/e2e/install_suite_test.go
  tests/e2e/plugins_helpers.go
  tests/e2e/plugins_suite_test.go
  tests/e2e/resources.go
  tests/e2e/restic_helpers.go
  tests/e2e/restic_suite_test.go
  tests/e2e/velero_helpers.go
Labels: ok-to-test

#195 Fix registry secret env vars
  controllers/registry.go
  controllers/registry_test.go
  cover.out
  go.mod
  go.sum
  pkg/credentials/credentials.go
Labels: operator-dev

#198 Change parameter scc instead of pointing to new scc object
  controllers/velero.go
Labels: kind/bug, operator-dev

#227 Fix velero resource requirements and add velero deployment unit tests
  controllers/velero.go
  controllers/velero_test.go
  cover.out
  go.mod
  go.sum
Labels: operator-dev

#229 Revert "noobaa skeleton (#216)"
  controllers/noobaa.go
  go.mod
  go.sum
Labels: lgtm

#213 Add BackupsStorageLocation Validations
  controllers/bsl.go
  controllers/bsl_test.go
  controllers/registry.go
  cover.out
Labels: operator-dev

#238 Add restic restore helper config
  controllers/restic.go
  controllers/restic_test.go
  controllers/velero_controller.go
  cover.out
  go.sum
Labels: operator-dev

#255 ci-Dockerfile for test image
  Makefile
  build/ci-Dockerfile
Labels: lgtm

#254 Add bsl-provider mapping validation
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/bsl.go
  controllers/bsl_test.go
  controllers/vsl.go
  cover.out
Labels: operator-dev
