Repository openshift/oadp-operator, pull requests merged in 2021-09, with the labels that each got.

#242 Refactor restic ds controller to use velero install pkg
  controllers/restic.go
  controllers/restic_test.go
  pkg/common/common.go
  pkg/credentials/credentials.go
Labels: operator-dev

#260 Update ci-Dockerfile
  build/ci-Dockerfile
Labels: lgtm

#263 Preserve owner references with install pkg changes
  controllers/restic.go
  controllers/velero.go
Labels: lgtm

#256 Add registry svc, route and configmap
  controllers/registry.go
  controllers/registry_test.go
  controllers/velero_controller.go
  main.go
Labels: operator-dev

#280 Update ci-Dockerfile for test-oadp-operator
  build/ci-Dockerfile
Labels: lgtm

#281 Update ci-Dockerfile with go mod download
  build/ci-Dockerfile
Labels: lgtm

#284 Change permissions to tests for CI
  tests/e2e/apps.go
  tests/e2e/backup.go
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/common.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/install_suite_test.go
  tests/e2e/plugins_helpers.go
  tests/e2e/plugins_suite_test.go
  tests/e2e/restic_helpers.go
  tests/e2e/restic_suite_test.go
  tests/e2e/restore.go
  tests/e2e/sample-applications/mssql-persistent/mssql-persistent-template.yaml
  tests/e2e/velero_helpers.go
Labels: lgtm

#273 pod dns config
  api/v1alpha1/velero_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/oadp.openshift.io_veleroes.yaml
  controllers/registry.go
  controllers/registry_test.go
  controllers/restic.go
  controllers/restic_test.go
  controllers/velero.go
  controllers/velero_test.go
  cover.out
Labels: lgtm

#300 NIT submitcoverage -> submit-coverage, removed test_submitcoverage, codecov....wait_for_ci:no
  .github/workflows/go-tests.yml
  Makefile
  codecov.yml
Labels: lgtm

#307 Olm managed field check fix, description fix
  api/v1alpha1/velero_types.go
  config/crd/bases/oadp.openshift.io_veleroes.yaml
  controllers/velero.go
Labels: operator-dev

#311 add troubleshooting section
  README.md
  TROUBLESHOOTING.md
Labels: documentation, lgtm

#316 Fix provider-plugin validation
  controllers/bsl.go
Labels: operator-dev

#323 Add regsitry kill switch
  api/v1alpha1/velero_types.go
  config/crd/bases/oadp.openshift.io_veleroes.yaml
  controllers/registry.go
Labels: operator-dev

#326 Add support for registry backed by GCP BSL
  controllers/bsl.go
  controllers/registry.go
  controllers/registry_test.go
  pkg/credentials/credentials.go
Labels: operator-dev

#319 Add support for registry backed by Azure BSL
  controllers/bsl.go
  controllers/registry.go
  controllers/registry_test.go
  pkg/credentials/credentials.go
Labels: operator-dev

#334 Fix registry issues
  controllers/bsl.go
  controllers/bsl_test.go
  controllers/registry.go
  controllers/registry_test.go
  controllers/restic_test.go
  controllers/velero_controller.go
  pkg/credentials/credentials.go
Labels: operator-dev

#348 Add Velero CR spec descriptions to work with `oc explain`
  api/v1alpha1/velero_types.go
  config/crd/bases/oadp.openshift.io_veleroes.yaml
Labels: operator-dev
