Repository openshift/oadp-operator, pull requests merged in 2021-11, with the labels that each got.

#450 Add supported multiarch labels
  deploy/olm-catalog/bundle/manifests/oadp-operator.v99.0.0.clusterserviceversion.yaml
Labels: lgtm

#472 Add OADP API Validator
  controllers/dpa_controller.go
  controllers/validator.go
  controllers/validator_test.go
  go.sum
Labels: operator-dev

#479 Rebase changes with the new OADP API
  Makefile
  config/samples/oadp_v1alpha1_velero_gcp.yaml
  go.sum
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/common.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/velero_deployment_suite_test.go
  tests/e2e/velero_helpers.go
Labels: needs-rebase
