Repository openshift/oadp-operator, pull requests merged in 2021-10, with the labels that each got.

#356 nit on old namespace name
  docs/developer/install_non-olm.md
Labels: needs-ok-to-test, lgtm

#366 missing single tick
  docs/examples/stateless.md
Labels: needs-ok-to-test

#375 typo: happend -> happened
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: lgtm

#397 Add operator labels
  controllers/bsl.go
  controllers/bsl_test.go
  controllers/registry.go
  controllers/registry_test.go
  controllers/restic.go
  controllers/restic_test.go
  controllers/velero.go
  controllers/velero_test.go
Labels: operator-dev
