Repository openshift/oadp-operator, pull requests merged in 2022-01, with the labels that each got.

#410 Enable ingestion of the exposed metrics by openshift-montoring
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/dpa_controller.go
  controllers/monitor.go
  controllers/monitor_test.go
  controllers/velero.go
  controllers/velero_test.go
  go.mod
  go.sum
  main.go
  tests/e2e/subscription_suite_test.go
  tests/e2e/velero_helpers.go
Labels: operator-dev

#537 OADP-200: Limit velero servicemonitor to keep bounded cardinality
  controllers/monitor.go
  controllers/monitor_test.go
Labels: lgtm, operator-dev

#528 Adding secrets watch
  controllers/bsl.go
  controllers/dpa_controller.go
  controllers/vsl.go
Labels: ok-to-test

#540 made tests' structure more generic
  Makefile
  docs/developer/TESTING.md
  go.sum
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/common.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/scripts/aws_settings.sh
  tests/e2e/subscription_helpers.go
  tests/e2e/subscription_suite_test.go
  tests/e2e/templates/default_settings.json
  tests/e2e/velero_deployment_suite_test.go
  tests/e2e/velero_helpers.go
Labels: ok-to-test

#543 Update Makefile
  Makefile
Labels: needs-ok-to-test
