Repository openshift/oadp-operator, pull requests merged in 2022-06, with the labels that each got.

#717 Remove NoDefaultBackupLocation e2e entry + registry probe timeout bump (fix azure flakes)
  controllers/registry.go
  controllers/registry_test.go
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/lib/backup.go
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/lib/velero_helpers.go
Labels: lgtm

#732 Makefile envtest patch for darwin/arm64
  Makefile
Labels: testing, lgtm

#718 oadp-1.0: Bump registry readiness probe timeout to 10s
  controllers/registry.go
  controllers/registry_test.go
Labels: testing

#745 Update perms for snapshot.storage.k8s.io
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: lgtm

#746 Add missed err handling
  controllers/velero.go
Labels: lgtm
