Repository openshift/oadp-operator, pull requests merged in 2022-05, with the labels that each got.

#624 Adding function to verify Backup / Restore data
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/lib/apps.go
Labels: testing

#654 B/R e2e add velero restic DC workaround, describe, namespace events, wait for CSI snapshot to be ready, IsDCReady wait for builds, azure-rg
  go.mod
  go.sum
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/lib/apps.go
  tests/e2e/lib/backup.go
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/lib/restore.go
  tests/e2e/lib/velero_helpers.go
  tests/e2e/scripts/azure_settings.sh
Labels: testing

#652 Replace carriage return when getting provider secrets for registry + E2E changes
  controllers/registry.go
  controllers/registry_test.go
  pkg/credentials/credentials.go
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/utils/common_utils.go
Labels: kind/bug, testing

#592 OADP Blog init + odf-oadp blog
  blogs/oadp-odf/OADP-OLM-1.png
  blogs/oadp-odf/ODFfinishedInstall.png
  blogs/oadp-odf/ODFlocalStorageDev.png
  blogs/oadp-odf/ObjectBucketClaimCreate.png
  blogs/oadp-odf/ObjectBucketClaimFields.png
  blogs/oadp-odf/ObjectBucketClaimReady.png
  blogs/oadp-odf/backupCreateInstance.png
  blogs/oadp-odf/backupRocketChat.png
  blogs/oadp-odf/create-dpa-cr-yaml.png
  blogs/oadp-odf/createRestoreInstance.png
  blogs/oadp-odf/deleteRocketChat.png
  blogs/oadp-odf/firstMessage.png
  blogs/oadp-odf/localStorage.png
  blogs/oadp-odf/oadp-blog.md
  blogs/oadp-odf/obc-default-oadp-bucket.png
  blogs/oadp-odf/odfInstall.png
  blogs/oadp-odf/operatorhub.png
  blogs/oadp-odf/readyToUse.png
  blogs/oadp-odf/restoreRocketChat.png
  blogs/oadp-odf/rocketChatReady.png
  blogs/oadp-odf/secretKeyValCreate.png
  blogs/oadp-odf/secretKeyValFields.png
Labels: documentation

#639 VSCode Debugging launch template. e2e accept environment flags.
  docs/developer/testing/AttatchingIDEDebuggers.md
  tests/e2e/e2e_suite_test.go
Labels: testing

#653 e2e retries CreateOrUpdate on DPA to resolve "... please apply your changes to the latest version ..."
  tests/e2e/lib/dpa_helpers.go
Labels: testing

#649 replace the parks-app with todolist on mongo
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/sample-applications/deprecated/parks-app/manifest.yaml
  tests/e2e/sample-applications/deprecated/parks-app/manifest4.8.yaml
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent-csi-template.yaml
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent.yaml
Labels: testing

#662 [OADP-460] Don't mount cloud provider secret volumes with NoDefaultBackupLocation
  controllers/validator.go
  controllers/velero.go
  controllers/velero_test.go
  docs/credentials.md
  pkg/credentials/credentials.go
Labels: do-not-merge/hold

#597 Datamover CRD design
  docs/design/datamover.md
  docs/images/datamovercrd.png
Labels: kind/design

#711 OADP-535 allow for nullable resource allocations
  api/v1alpha1/oadp_types.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
Labels: lgtm
