Repository openshift/oadp-operator, pull requests merged in 2023-07, with the labels that each got.

#1083 add rosa sts mobb doc to troubleshooting
  docs/TROUBLESHOOTING.md
Labels: approved, lgtm

#1080 OADP-2048:Add volsync cron expression support
  api/v1alpha1/oadp_types.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/datamover.go
Labels: approved, lgtm, jira/valid-reference

#1084 [oadp-1.2] OADP-2048:Add volsync cron expression support (#1080)
  api/v1alpha1/oadp_types.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/datamover.go
Labels: approved, lgtm, jira/valid-reference

#1082 Use of OpenShift workload monitoring stack for the OADP
  docs/examples/manifests/user_monitoring/1_enable_user_workload_monitoring.yaml
  docs/examples/manifests/user_monitoring/2_configure_user_workload_monitoring.yaml
  docs/examples/manifests/user_monitoring/3_create_oadp_service_monitor.yaml
  docs/examples/manifests/user_monitoring/4_create_oadp_alert_rule.yaml
  docs/images/metrics_targets.png
  docs/images/oadp_backup_failing_alert.png
  docs/images/oadp_metrics_query.png
  docs/oadp_monitoring.md
Labels: approved, lgtm

#1090 Update docs to reflect new VSL credentials field
  docs/credentials.md
Labels: approved, lgtm

#1087 Datamover blog update for 1.2.x
  blogs/data-mover/data-mover-1.2.0-overview.md
  blogs/data-mover/data-mover-backup.png
  blogs/data-mover/data-mover-restore.png
Labels: approved, lgtm

#1091 point to 1.2 branch for velero and csi plugin on master
  build/ci-Dockerfile
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/suite_test.go
  controllers/velero_test.go
  pkg/common/common.go
  pkg/credentials/credentials_test.go
  tests/e2e/lib/velero_helpers.go
  tests/e2e/must-gather_suite_test.go
  tests/e2e/utils/common_utils.go
Labels: approved, lgtm

#1081 [oadp-1.2] OADP-1887: Disable cluster monitoring and remove ServiceMonitor
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp-operator_monitoring.coreos.com_v1_prometheusrule.yaml
  config/manager/manager.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/prometheus/oadp-metrics-recording-rule.yaml
  controllers/dpa_controller.go
  controllers/monitor.go
  controllers/monitor_test.go
  deploy/disconnected-prep.sh
Labels: approved, lgtm, jira/valid-reference

#1095 ci-Dockerfile: chmod go env GOCACHE
  build/ci-Dockerfile
Labels: approved

#1096 ci-Dockerfile: `git config core.filemode false`
  build/ci-Dockerfile
Labels: approved

#1099 Revert to master ci-Dockerfile except `go version`
  build/ci-Dockerfile
Labels: approved

#1097 Fix typo in CRD description
  api/v1alpha1/oadp_types.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
Labels: approved, lgtm, ok-to-test
