Repository openshift/oadp-operator, pull requests merged in 2023-08, with the labels that each got.

#1107 Velero Built-in Data Mover design for OADP
  docs/design/upstream-datamover.md
Labels: approved, lgtm

#1101 Node Agent Configuration design and design template
  docs/design/_template.md
  docs/design/node_agent_config-design.md
Labels: do-not-merge/hold, approved

#1110 Add new OADP versions to velero support matrix
  README.md
Labels: approved, lgtm

#1118 feat: Add uninstall command
  Makefile
  docs/developer/install_from_source.md
  docs/developer/olm_hacking.md
  docs/developer/testing/AttatchingIDEDebuggers.md
Labels: approved, lgtm, ok-to-test

#1113 Mysql restic e2e test failure on ocp4.12
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent.yaml
Labels: do-not-merge/hold, approved

#1122 Mysql-restic template to aligned with changed pod security on OCP-4.12
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent.yaml
Labels: approved, lgtm

#1109 WIF support design
  docs/design/gcp-wif-support_design.md
Labels: approved, lgtm

#1100 oadp-1.2: Fix typo in CRD description
  api/v1alpha1/oadp_types.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
Labels: approved, lgtm

#1124 Mysql-restic template to aligned with changed pod security on OCP-4.1…
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent.yaml
Labels: approved, lgtm

#1125 Update velero dep to 1.11.1
  Dockerfile
  build/ci-Dockerfile
  go.mod
  go.sum
Labels: approved, lgtm

#1126 OADP-1057: CloudStorageLocation Prefix/CACert support
  api/v1alpha1/cloud_storage_types.go
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/bsl.go
  controllers/bsl_test.go
  controllers/dpa_controller.go
  controllers/validator.go
  controllers/validator_test.go
  controllers/vsl.go
  controllers/vsl_test.go
  tests/e2e/lib/velero_helpers.go
  tests/e2e/lib/velero_helpers_test.go
Labels: approved, lgtm, jira/valid-reference

#1135 master: OADP-2377 Add mustgather registry image to relatedImage
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm

#1132 OADP-2094: RestoreResourcePriorities for OpenShift workloads with SecurityContextConstraints
  api/v1alpha1/oadp_types.go
  controllers/velero_test.go
Labels: approved, lgtm, jira/valid-reference

#1136 oadp-1.2: OADP-2377 Add mustgather registry image to relatedImage
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm

#1140 OADP-2420: RestoreResourcePriorities for OpenShift workloads with SecurityContextConstraints
  api/v1alpha1/oadp_types.go
  controllers/velero_test.go
Labels: approved, jira/valid-reference

#1133 OADP-2410: Manual workaround for restic restore failure due to changed PSA polic…
  docs/TROUBLESHOOTING.md
Labels: approved, lgtm, jira/valid-reference

#1098 fix: defaultPlugins validations
  api/v1alpha1/cloud_storage_types.go
  api/v1alpha1/oadp_types.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
Labels: approved, lgtm, ok-to-test

#1102 Adds kopia/restic uploader type
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  config/samples/oadp_v1alpha1_dpa.yaml
  controllers/dpa_controller.go
  controllers/nodeagent.go
  controllers/nodeagent_test.go
  controllers/validator.go
  controllers/validator_test.go
  controllers/velero.go
  docs/TROUBLESHOOTING.md
  docs/config/azure_plugin.md
  docs/config/bsl_and_vsl.md
  docs/config/custom_plugin_images.md
  docs/config/noobaa/install_oadp_noobaa.md
  docs/config/resource_req_limits.md
  docs/config/self_signed_certs.md
  docs/credentials.md
  docs/design/node_agent_config-design.md
  docs/examples/CSI/csi_example.md
  docs/examples/data_mover.md
  docs/examples/datamover_advanced_voloptions.md
  docs/examples/stateful.md
  docs/examples/stateless.md
  docs/install_olm.md
  docs/upgrade.md
  pkg/velero/server/config.go
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/lib/dpa_helpers.go
Labels: approved, lgtm

#1143 fix: [oadp-1.1] OADP-2094 Always check restore resource priorities
  api/v1alpha1/oadp_types.go
  controllers/velero.go
  controllers/velero_test.go
  pkg/common/common.go
Labels: approved, lgtm, ok-to-test

#1146 fix: [oadp-1.2] OADP-2094 Always check restore resource priorities
  api/v1alpha1/oadp_types.go
  controllers/velero.go
  controllers/velero_test.go
  pkg/common/common.go
  tests/e2e/must-gather_suite_test.go
  tests/e2e/utils/common_utils.go
Labels: approved, lgtm, ok-to-test
