Repository openshift/oadp-operator, pull requests merged in 2023-06, with the labels that each got.

#1059 Remove moversecuritycontent instructions for dm
  docs/examples/datamover_advanced_voloptions.md
Labels: approved, lgtm

#1060 Add note about privileged annotation not needed for OADP 1.2
  docs/examples/data_mover.md
Labels: approved, lgtm

#1055 oadp-1.2: OADP-2047: Make data mover dummy pod configurable
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/datamover.go
  controllers/datamover_test.go
  pkg/common/common.go
Labels: approved, lgtm, jira/valid-reference

#1058 OADP-1941: Default datamover SC and add mover annotation
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/datamover.go
  pkg/common/common.go
Labels: approved, lgtm, jira/valid-reference

#1067 Fix 3 CSI Volumes sample app deployment issue
  tests/e2e/sample-applications/minimal-8csivol/minimal-3csivol.yaml
Labels: approved, lgtm

#1068 Add a way to override velero/datamover replicas for debug purposes.
  controllers/datamover.go
  controllers/datamover_test.go
  controllers/velero.go
  controllers/velero_test.go
Labels: approved, lgtm

#1066 Tekton based OADP non-admin example blog
  blogs/tekton-oadp-nonadmin/README.md
  blogs/tekton-oadp-nonadmin/check_prerequisites.sh
  blogs/tekton-oadp-nonadmin/demo_users/01-new-project-request_template.yaml
  blogs/tekton-oadp-nonadmin/demo_users/create_demousers.sh
  blogs/tekton-oadp-nonadmin/demo_users/oauth.yaml
  blogs/tekton-oadp-nonadmin/demo_users/user.yaml
  blogs/tekton-oadp-nonadmin/install.sh
  blogs/tekton-oadp-nonadmin/install_templates/02-tekton-operator.yaml
  blogs/tekton-oadp-nonadmin/install_templates/templates/03-rbac-pipeline-role.yaml
  blogs/tekton-oadp-nonadmin/install_templates/templates/04-service-account_template.yaml
  blogs/tekton-oadp-nonadmin/install_templates/templates/05-build-and-deploy.yaml
  blogs/tekton-oadp-nonadmin/oadp-tekton-container/Dockerfile
  blogs/tekton-oadp-nonadmin/oadp-tekton-container/advanced_backup.yaml
  blogs/tekton-oadp-nonadmin/oadp-tekton-container/backup.yaml
  blogs/tekton-oadp-nonadmin/oadp-tekton-container/check_backup_namespace.sh
  blogs/tekton-oadp-nonadmin/oadp-tekton-container/get_restore_namespace.sh
  blogs/tekton-oadp-nonadmin/oadp-tekton-container/restore.yaml
  blogs/tekton-oadp-nonadmin/readme_img/OADP_Non_Admin.png
  blogs/tekton-oadp-nonadmin/readme_img/backup_pipeline_done.png
  blogs/tekton-oadp-nonadmin/readme_img/backup_pipeline_run.png
  blogs/tekton-oadp-nonadmin/readme_img/oadp_non_admin_arch.png
  blogs/tekton-oadp-nonadmin/readme_img/openshift_pipelines.png
  blogs/tekton-oadp-nonadmin/readme_img/pipeline_actions.png
  blogs/tekton-oadp-nonadmin/readme_img/restore_pipeline.png
  blogs/tekton-oadp-nonadmin/readme_img/restore_pipeline_done.png
  blogs/tekton-oadp-nonadmin/readme_img/restore_pipeline_in_progress.png
  blogs/tekton-oadp-nonadmin/readme_img/restore_pipeline_run.png
  blogs/tekton-oadp-nonadmin/readme_img/trigger_backup.png
Labels: approved, lgtm

#1071 update non-admin arch diagram
  blogs/tekton-oadp-nonadmin/readme_img/oadp_non_admin_arch.png
Labels: approved

#1072 Update README.md
  blogs/tekton-oadp-nonadmin/README.md
Labels: approved

#1070 update the mysql-stateful app instructions for PV and data
  docs/examples/stateful.md
Labels: approved, lgtm

#1078 OADP-2175: Make use of restic secret to pass datamover retain policy instead of datamover config map
  controllers/datamover.go
Labels: approved, lgtm, jira/valid-reference

#1076 Troubleshooting update
  docs/TROUBLESHOOTING.md
Labels: approved, lgtm

#1074 Cheat sheet
  docs/oadp_cheat_sheat.md
Labels: approved, lgtm

#1075 Restic troubleshooting
  docs/restic_troubleshooting.md
Labels: approved
