Repository openshift/oadp-operator, pull requests merged in 2023-12, with the labels that each got.

#1248 [oadp-1.3] fix: README 1.3 CI links
  README.md
Labels: approved

#1251 Updating Velero version for OADP 1.3.0
  README.md
Labels: approved, lgtm

#1219 updated OADP-1.3.0 DM blog post
  blogs/data-mover/data-mover-1.2/data-mover-1.2.0-overview.md
  blogs/data-mover/data-mover-1.2/data-mover-backup.png
  blogs/data-mover/data-mover-1.2/data-mover-overview.md
  blogs/data-mover/data-mover-1.2/data-mover-restore.png
  blogs/data-mover/data-mover-1.3/backup-13-workflow.png
  blogs/data-mover/data-mover-1.3/data-mover-1.3.0-overview.md
  blogs/data-mover/data-mover-1.3/data-mover-13-backup-sequence.png
  blogs/data-mover/data-mover-1.3/data-mover-13-restore-sequence.png
  blogs/data-mover/data-mover-1.3/restore-13-workflow.png
Labels: approved, lgtm

#1242 Indicate to user a new vsc def is required
  docs/examples/CSI/csi_example.md
Labels: approved, lgtm

#1255 fix: Fix codecov post job
  Makefile
Labels: approved, lgtm, CI
