Repository openshift/oadp-operator, pull requests merged in 2023-04, with the labels that each got.

#946 Update image tags to oadp-1.2 in csv
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
  controllers/velero_test.go
  pkg/common/common.go
  pkg/credentials/credentials_test.go
Labels: lgtm, FeatureFreeze

#965 oadp-1.0: e2e Don't delete "" namespace when Skip() is called.
  tests/e2e/backup_restore_suite_test.go
Labels: testing

#971 Update oadp velero version relationship table.
  README.md
Labels: lgtm

#973 OADP-1511, OADP-1670: Add owner reference to cloud storage BSLs.
  controllers/bsl.go
  controllers/bsl_test.go
  controllers/vsl_test.go
Labels: jira/valid-reference

#978 OADP-218: Allow for BSL name to be defined in DPA CR
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/bsl.go
Labels: approved, lgtm, jira/valid-reference

#977 oadp-1.1: privileged movers e2e
  .gitignore
  Makefile
  api/v1alpha1/groupversion_info.go
  build/ci-Dockerfile
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/bucket_controller.go
  controllers/datamover.go
  controllers/suite_test.go
  controllers/velero.go
  go.mod
  go.sum
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/lib/apps.go
  tests/e2e/lib/dpa_helpers.go
Labels: approved, lgtm

#988 README.md: remove prow 4.8, 4.9 badges
  README.md
Labels: approved, lgtm

#985 oadp-1.2: go get openshift/velero:oadp-1.2 && go fmt ./...
  api/v1alpha1/groupversion_info.go
  controllers/datamover.go
  controllers/velero.go
  go.mod
  go.sum
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/lib/apps.go
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/lib/restore.go
Labels: approved, lgtm

#989 OADP-708/OADP-1526: Validation for BSL/VSL credentials secrets
  api/v1alpha1/oadp_types.go
  controllers/validator.go
  controllers/validator_test.go
  controllers/velero.go
  controllers/velero_test.go
  controllers/vsl.go
  go.mod
  go.sum
Labels: approved, lgtm, jira/valid-reference
