Repository openshift/oadp-operator, pull requests merged in 2023-11, with the labels that each got.

#1184 fix: make test command succeeds locally
  Makefile
  controllers/bsl_test.go
  controllers/validator.go
  controllers/validator_test.go
Labels: approved, lgtm

#1210 Update OADP Readme to point to proper product docs
  README.md
Labels: approved, lgtm

#1208 Update the upgrade instructions
  docs/install_olm.md
  docs/upgrade_1-1_to_1-2.md
  docs/upgrade_1-2_to_1-3.md
Labels: approved, lgtm

#1200 OADP-2959: Add missing descriptions to all CRDs
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
Labels: approved, jira/valid-reference

#1213 [oadp-1.2] [OADP-2959] Add missing descriptions to all CRDs (#1200)
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1212 Remove VSB and VSR from OADP 1.3+
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
  docs/API_ref.md
  docs/examples/datamover_resources.sh
Labels: approved, lgtm

#1217 fix: [oadp-1.2] Remove unused code in OADP 1.2
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1220 OADP-3054: BSL default configuration validation
  controllers/bsl.go
  controllers/bsl_test.go
  controllers/validator_test.go
Labels: approved, jira/valid-reference

#1205 fix: One kubernetes client per E2E suite run
  Makefile
  docs/developer/testing/TESTING.md
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/lib/apps.go
  tests/e2e/lib/backup.go
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/lib/kube_helpers.go
  tests/e2e/lib/nodeagent_helpers.go
  tests/e2e/lib/plugins_helpers.go
  tests/e2e/lib/registry_helpers.go
  tests/e2e/lib/restore.go
  tests/e2e/lib/subscription_helpers.go
  tests/e2e/lib/velero_helpers.go
  tests/e2e/must-gather_suite_test.go
  tests/e2e/subscription_suite_test.go
Labels: do-not-merge/hold, approved, lgtm

#1231 fix: Periodic E2E tests run links in README
  README.md
Labels: approved, lgtm

#1232 fix: Remove 1.3 code from master branch
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/datamover.go
  controllers/dpa_controller.go
  controllers/nodeagent.go
  controllers/validator.go
Labels: approved, lgtm

#1237 doc: How to update OCP version jobs in CI
  README.md
  docs/developer/PROW_CI.md
  docs/developer/testing/TESTING.md
Labels: approved, lgtm

#1239 fix: Remove unused CI file
  .ci-operator.yaml
Labels: approved, lgtm
