Repository openshift/oadp-operator, pull requests merged in 2023-09, with the labels that each got.

#1145 Velero datamover pr
  Dockerfile
  Makefile
  build/ci-Dockerfile
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  bundle/manifests/velero.io_backuprepositories.yaml
  bundle/manifests/velero.io_backups.yaml
  bundle/manifests/velero.io_backupstoragelocations.yaml
  bundle/manifests/velero.io_datadownloads.yaml
  bundle/manifests/velero.io_datauploads.yaml
  bundle/manifests/velero.io_deletebackuprequests.yaml
  bundle/manifests/velero.io_downloadrequests.yaml
  bundle/manifests/velero.io_podvolumebackups.yaml
  bundle/manifests/velero.io_podvolumerestores.yaml
  bundle/manifests/velero.io_restores.yaml
  bundle/manifests/velero.io_schedules.yaml
  bundle/manifests/velero.io_serverstatusrequests.yaml
  bundle/manifests/velero.io_volumesnapshotlocations.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/velero.io_backuprepositories.yaml
  config/crd/bases/velero.io_backups.yaml
  config/crd/bases/velero.io_backupstoragelocations.yaml
  config/crd/bases/velero.io_datadownloads.yaml
  config/crd/bases/velero.io_datauploads.yaml
  config/crd/bases/velero.io_deletebackuprequests.yaml
  config/crd/bases/velero.io_downloadrequests.yaml
  config/crd/bases/velero.io_podvolumebackups.yaml
  config/crd/bases/velero.io_podvolumerestores.yaml
  config/crd/bases/velero.io_restores.yaml
  config/crd/bases/velero.io_schedules.yaml
  config/crd/bases/velero.io_serverstatusrequests.yaml
  config/crd/bases/velero.io_volumesnapshotlocations.yaml
  config/crd/kustomization.yaml
  config/manager/manager.yaml
  controllers/bucket_controller.go
  controllers/velero_test.go
  go.mod
  go.sum
  pkg/common/common.go
  pkg/credentials/credentials_test.go
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/lib/velero_helpers.go
  tests/e2e/must-gather_suite_test.go
Labels: approved, lgtm

#1148 fix: README OCP versions for E2E tests
  README.md
Labels: approved, lgtm

#1103 Add .dockerignore
  .dockerignore
Labels: approved, lgtm

#1147 OADP-2505: Add additional types to default restore priorities
  api/v1alpha1/oadp_types.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/velero.go
  controllers/velero_test.go
  pkg/common/common.go
  pkg/velero/server/config.go
Labels: approved, lgtm, jira/valid-reference

#1152 Welcome docs back to Dockerfiles
  .dockerignore
Labels: approved

#1139 fix: OADP-2688 Always check restore resource priorities
  api/v1alpha1/oadp_types.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/velero.go
  controllers/velero_test.go
  pkg/common/common.go
  pkg/velero/server/config.go
Labels: approved, lgtm, ok-to-test

#1106 OADP-2112: Support the standardized STS configuration flow via OLM and CCO for OADP
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/bucket_controller.go
  main.go
  pkg/bucket/client.go
  pkg/common/common.go
Labels: approved, lgtm, jira/valid-reference

#1156 New infrastructure annotation format (#1155)
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1158 Document workaround for combining must-gather options.
  must-gather/README.md
Labels: approved, lgtm

#1112 implement GCP WIF support
  controllers/dpa_controller.go
  controllers/velero.go
  controllers/velero_test.go
  pkg/client/client.go
  pkg/credentials/credentials.go
  pkg/credentials/credentials_test.go
  pkg/credentials/gcp.go
Labels: approved, lgtm

#1159 OADP-1737: Fix defaultl credentials logic
  controllers/velero.go
Labels: approved, lgtm, jira/valid-reference

#1162 velero 1.12.0 release update
  go.mod
  go.sum
Labels: approved, lgtm

#1137 OADP-2139: [oadp-1.2] remove old restic DaemonSet
  controllers/dpa_controller.go
  controllers/restic.go
  docs/upgrade1-1.md
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#1151 fix: [oadp-1.1] CRD description of default restore resource priorities
  api/v1alpha1/oadp_types.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/velero.go
  controllers/velero_test.go
  pkg/common/common.go
  pkg/velero/server/config.go
Labels: approved, lgtm

#1153 OADP-2745: Testing instructions for AWS/IBM Cloud
  Makefile
  docs/developer/testing/TESTING.md
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/e2e_suite_test.go
Labels: approved, lgtm, jira/valid-reference

#1167 fix: Remove 1.1 daemonset
  controllers/dpa_controller.go
  controllers/nodeagent.go
  docs/upgrade_1-1_to_1-2.md
Labels: approved, lgtm

#1165 oadp-1.1: Fix oadp operator image tag
  Makefile
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test

#1168 add pvc configs for use of default storage class
  docs/developer/testing/TESTING.md
  tests/e2e/sample-applications/mongo-persistent/pvc/default_sc.yaml
  tests/e2e/sample-applications/mysql-persistent/pvc-twoVol/default_sc.yaml
  tests/e2e/sample-applications/mysql-persistent/pvc/default_sc.yaml
Labels: approved, lgtm

#1166 oadp-1.2: Correct operator name in bundle to oadp-operator.v1.2.2
  Makefile
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test
