Repository openshift/oadp-operator, pull requests merged in 2023-10, with the labels that each got.

#1130 Correct indentation re:PSA policy warnings
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent.yaml
Labels: approved, lgtm

#1169 OADP-659 Remove HTTP/HTTPS port numbers from AWS S3 URLs.
  controllers/bsl.go
  pkg/common/common.go
Labels: approved, lgtm

#1172 OADP-2796: update velero dep to pull in block mode changes
  controllers/nodeagent.go
  controllers/nodeagent_test.go
  go.mod
  go.sum
Labels: approved, lgtm, jira/valid-reference

#1170 OADP-2747: Re-enable DataMover E2E tests
  Makefile
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/lib/backup.go
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/lib/restic_helpers.go
  tests/e2e/must-gather_suite_test.go
  tests/e2e/subscription_suite_test.go
  tests/e2e/volsync/volsync-sub.yaml
Labels: approved, lgtm, jira/valid-reference

#1177 OADP-659 Avoid overwriting good hostname.
  pkg/common/common.go
Labels: approved, lgtm

#1179 OADP-2686: add ACM resources to restore priority
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/velero_test.go
  pkg/common/common.go
  pkg/velero/server/config.go
Labels: approved, lgtm, jira/valid-reference

#1182 OADP-659/OADP-2862 Add unit tests for #1169 and #1177.
  pkg/common/common_test.go
Labels: approved, lgtm

#1183 fix: Update CI links in README
  README.md
Labels: approved, lgtm

#1185 oadp-1.0: Fix CVE-2023-39325
  go.mod
  go.sum
Labels: approved

#1188 oadp-1.1: x/net v0.17.0
  go.mod
  go.sum
Labels: approved

#1189 oadp-1.0: golang 1.19
  go.mod
  go.sum
Labels: approved

#1187 oadp-1.2: x/net v0.17.0
  go.mod
  go.sum
Labels: approved

#1186 Updating velero dep after rebase 16 Oct 2023
  go.mod
  go.sum
Labels: approved, lgtm

#1197 Update velero dep after rebase 2023-10-24
  go.mod
  go.sum
  tests/e2e/lib/velero_helpers.go
Labels: approved, lgtm

#1180 OADP-1.2 Cherry-pick of OADP-659: Remove HTTP/HTTPS port numbers from AWS S3 URLs.
  controllers/bsl.go
  pkg/common/common.go
Labels: approved, lgtm, jira/valid-reference

#1199 start a kopia troubleshooting doc
  docs/kopia_troubleshotting.md
Labels: approved, lgtm

#1191 Add logic to fail DPA reconcile on wrong BSL secret key
  controllers/bsl_test.go
  controllers/validator.go
  controllers/validator_test.go
Labels: approved, lgtm, ok-to-test

#1174 OADP-2746: Update oadp-operator master branch for RESTIC && KOPIA
  docs/TROUBLESHOOTING.md
  docs/scripts/dc-post-restore.sh
  docs/scripts/dc-restic-post-restore.sh
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/lib/apps.go
  tests/e2e/lib/backup.go
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/lib/nodeagent_helpers.go
  tests/e2e/lib/velero_helpers.go
  tests/e2e/must-gather_suite_test.go
  tests/e2e/subscription_suite_test.go
Labels: approved, jira/valid-reference

#1193 OADP-2770: Mongodb e2e datamover with block mode
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent-block.yaml
  tests/e2e/sample-applications/mongo-persistent/pvc/aws-block-mode.yaml
  tests/e2e/sample-applications/mongo-persistent/pvc/azure-block-mode.yaml
  tests/e2e/sample-applications/mongo-persistent/pvc/default_sc-block-mode.yaml
  tests/e2e/sample-applications/mongo-persistent/pvc/gcp-block-mode.yaml
  tests/e2e/sample-applications/mongo-persistent/pvc/ibmcloud-block-mode.yaml
Labels: approved, jira/valid-reference

#1198 oadp-1.2: e2e: Add restore warning to errorIgnorePatterns
  tests/e2e/lib/velero_helpers.go
Labels: approved, lgtm

#1171 OADP-2767: Upgrade: Remove unbreaking references to VSM/Volsync DataMover
  Makefile
  README.md
  api/v1alpha1/oadp_types.go
  blogs/data-mover/data-mover-1.2.0-overview.md
  blogs/data-mover/data-mover-overview.md
  bundle/manifests/datamover.oadp.openshift.io_volumesnapshotbackups.yaml
  bundle/manifests/datamover.oadp.openshift.io_volumesnapshotrestores.yaml
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/datamover.oadp.openshift.io_volumesnapshotbackups.yaml
  config/crd/bases/datamover.oadp.openshift.io_volumesnapshotrestores.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/datamover.go
  controllers/datamover_test.go
  controllers/dpa_controller.go
  controllers/validator.go
  controllers/validator_test.go
  controllers/velero.go
  deploy/disconnected-prep.sh
  docs/TROUBLESHOOTING.md
  docs/config/plugins.md
  docs/credentials.md
  docs/examples/data_mover.md
  docs/oadp_cheat_sheet.md
  docs/restic_troubleshooting.md
  docs/upgrade_1-2_to_1-3.md
  must-gather/collection-scripts/gather_versions
  pkg/common/common.go
  pkg/credentials/credentials.go
  pkg/credentials/credentials_test.go
Labels: approved, lgtm, jira/valid-reference

#1207 OADP-2988 Fix CVE-2023-45142 otelhttp
  go.mod
  go.sum
Labels: approved, lgtm

#1209 fix: dc post restore script logic to delete disconnected pods
  docs/scripts/dc-post-restore.sh
Labels: approved, lgtm
