Repository openshift/oadp-operator, pull requests merged in 2023-02, with the labels that each got.

#895 OADP-1067: Set env vars on datamover deployment for batching
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/datamover.go
  controllers/datamover_test.go
Labels: jira/valid-reference

#896 OADP-1151: Provide an option to set volsync replicationsource prune interval
  api/v1alpha1/oadp_types.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/datamover.go
Labels: jira/valid-reference

#879 OADP-1224: restic node-agent refactor label
  controllers/restic.go
  controllers/restic_test.go
  controllers/velero_test.go
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/lib/restic_helpers.go
  tests/e2e/subscription_suite_test.go
Labels: jira/valid-reference

#899 OADP-1269: Integrate velero-plugin-for-vsm with OADP Operator
  api/v1alpha1/oadp_types.go
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/validator.go
  controllers/validator_test.go
  deploy/disconnected-prep.sh
  pkg/common/common.go
  pkg/credentials/credentials.go
  pkg/credentials/credentials_test.go
Labels: jira/valid-reference

#897 OADP-1231: Add config values for data mover
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/datamover.go
  controllers/dpa_controller.go
Labels: jira/valid-reference, custom_bell

#898 init use same resources as the main container
  controllers/velero_test.go
  pkg/credentials/credentials.go
Labels: lgtm, ok-to-test

#910 8pvc test template
  tests/e2e/sample-applications/minimal-8csivol/list.yaml
Labels: ¯\_(ツ)_/¯
