Repository openshift/oadp-operator, pull requests merged in 2023-05, with the labels that each got.

#995 Fix datamover volume options nil case
  controllers/datamover.go
Labels: approved, lgtm

#987 oadp-1.1: OADP-1557 Add all velero server args supported to DPA
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/bucket_controller.go
  controllers/common.go
  controllers/dpa_controller.go
  controllers/monitor.go
  controllers/restic.go
  controllers/restore_resource_version_priority.go
  controllers/validator.go
  controllers/velero.go
  controllers/velero_test.go
  go.mod
  go.sum
  pkg/common/common.go
  pkg/common/common_test.go
  pkg/klog/klog.go
  pkg/klog/zz_generated.deepcopy.go
  pkg/velero/client/config.go
  pkg/velero/client/zz_generated.deepcopy.go
  pkg/velero/server/args.go
  pkg/velero/server/config.go
  pkg/velero/server/zz_generated.deepcopy.go
Labels: approved, lgtm

#1001 add 8 and 3 vol b/r manifest and b/r crs
  tests/e2e/sample-applications/minimal-8csivol/minimal-3csivol-backup.yaml
  tests/e2e/sample-applications/minimal-8csivol/minimal-3csivol-restore.yaml
  tests/e2e/sample-applications/minimal-8csivol/minimal-3csivol.yaml
  tests/e2e/sample-applications/minimal-8csivol/minimal-8csivol-backup.yaml
  tests/e2e/sample-applications/minimal-8csivol/minimal-8csivol-restore.yaml
  tests/e2e/sample-applications/minimal-8csivol/minimal-8csivol.yaml
Labels: approved, lgtm

#999 Update VSB/VSR CRDs to add batchingStatus printer column
  bundle/manifests/datamover.oadp.openshift.io_volumesnapshotbackups.yaml
  bundle/manifests/datamover.oadp.openshift.io_volumesnapshotrestores.yaml
  config/crd/bases/datamover.oadp.openshift.io_volumesnapshotbackups.yaml
  config/crd/bases/datamover.oadp.openshift.io_volumesnapshotrestores.yaml
Labels: approved, lgtm

#994 OADP-1801: Include restic and velero binaries in must-gather image, and gather various pieces of version information.
  must-gather/Dockerfile
  must-gather/collection-scripts/debug/tail_failed_pods
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_versions
Labels: approved, lgtm, jira/valid-reference

#1005 add VERY basic block pv setup
  tests/e2e/sample-applications/block-pv/Dockerfile
  tests/e2e/sample-applications/block-pv/notes.txt
  tests/e2e/sample-applications/block-pv/pod.yaml
  tests/e2e/sample-applications/block-pv/pv.yaml
  tests/e2e/sample-applications/block-pv/pvc.yaml
Labels: approved, lgtm

#1007 OADP-1934: Remove hard-coded namespace from debug example.
  must-gather/collection-scripts/debug/tail_failed_pods
Labels: approved, lgtm, jira/valid-reference

#1008 OADP-1931: Update description in CSV
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#990 Redirect users to oc-explain for references.
  .gitignore
  docs/API_ref.md
Labels: approved

#1002 OADP-148 First attempt at speeding up must-gather.
  must-gather/Dockerfile
  must-gather/collection-scripts/gather_versions
  must-gather/collection-scripts/logs/gather_logs_backup
  must-gather/collection-scripts/logs/gather_logs_restore
Labels: approved, lgtm

#1012 OADP-1844: Validation to ensure vsm plugin is removed from DPA if DM is false
  controllers/validator.go
Labels: approved, lgtm, jira/valid-reference

#1014 update documentation for datamover and docs/faq
  README.md
  docs/examples/data_mover.md
Labels: approved, lgtm

#1015 OADP-1941: Default datamover moverSecurityContext to true
  api/v1alpha1/oadp_types.go
  controllers/datamover.go
Labels: approved, lgtm, jira/valid-reference

#1018 OADP-1927: Fix VSL secret validation
  controllers/vsl.go
Labels: approved, lgtm, jira/valid-reference

#1023 OADP-1927: Add unit test for custom BSL and VSL secret
  controllers/validator_test.go
Labels: approved, lgtm, jira/valid-reference

#1006 OADP-1821: storageClass mapping for data mover volumeOptions
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/datamover.go
  go.mod
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/lib/dpa_helpers_test.go
Labels: approved, jira/valid-reference

#1025 OADP-1821: storageClass mapping for data mover volumeOptions (#1006)
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/datamover.go
  go.mod
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/lib/dpa_helpers_test.go
Labels: approved, lgtm, jira/valid-reference

#1026 Remove reference to unknown revision `github.com/openshift/api v3.9.0`
  go.mod
  go.sum
Labels: approved, lgtm

#1022 set privledged to false
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent-twovol-csi.yaml
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent.yaml
Labels: approved

#1027 OADP-1931: Update description in CSV (#1008)
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#1031 e2e: Use readWriteOnce accessMode for sourceVolumeOptions
  tests/e2e/lib/dpa_helpers.go
Labels: approved, lgtm

#1024 Update openshift/velero references in go.mod
  Makefile
  api/v1alpha1/groupversion_info.go
  build/ci-Dockerfile
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/bucket_controller.go
  controllers/datamover.go
  controllers/suite_test.go
  controllers/velero_test.go
  go.mod
  go.sum
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/lib/apps.go
  tests/e2e/lib/restore.go
Labels: approved, lgtm

#1000 Check bundle is up to date in unit-test
  Makefile
Labels: approved, lgtm

#1036 OADP-1987: Correctly get backup/restore logs in must-gather.
  must-gather/collection-scripts/logs/gather_logs_backup
  must-gather/collection-scripts/logs/gather_logs_restore
Labels: approved, lgtm, jira/valid-reference

#1034 add samples for cephfs/rbd for documentation
  tests/e2e/sample-applications/mysql-persistent/pvc-twoVol/cephfs.yml
  tests/e2e/sample-applications/mysql-persistent/pvc-twoVol/cephrbd.yml
  tests/e2e/sample-applications/mysql-persistent/storageclass/cephfs-shallow.yml
  tests/e2e/sample-applications/mysql-persistent/storageclass/ocs-storagecluster-ceph-rbd.yaml
  tests/e2e/sample-applications/mysql-persistent/storageclass/ocs-storagecluster-cephfs.yaml
Labels: approved, lgtm

#1038 Doc with Datamover Advanced VolumeOptions Example
  docs/examples/datamover_advanced_voloptions.md
Labels: approved, lgtm

#1050 Remove test from docker-build
  Makefile
Labels: approved, lgtm

#1049 Add Note: CephsFS ShallowCopy not supported for datamover restore
  docs/examples/datamover_advanced_voloptions.md
Labels: approved, lgtm
