Repository openshift/oadp-operator, pull requests merged in 2024-02, with the labels that each got.

#1278 Fix OADP-3044: DPA doesnt report missing region error on adding profile: default
  controllers/bsl.go
  controllers/bsl_test.go
Labels: approved, lgtm, jira/valid-reference

#1303 Do not fail test on HCO removal timeout.
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm

#1294 fix: Refactor no default BSL code validation
  controllers/validator.go
  controllers/validator_test.go
Labels: approved, lgtm

#1302 BSL/VSL validation code cleanup
  controllers/bsl.go
  controllers/bsl_test.go
  controllers/validator.go
  controllers/vsl.go
Labels: approved, lgtm

#1315 CI: upload CirrOS disk image to DataVolume.
  tests/e2e/lib/virt_storage_helpers.go
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm

#1305 [oadp-1.3] update velero version number in go.mod to 1.12.3
  go.mod
Labels: approved, lgtm

#1318 OADP-3495: mark FIPS compliant flag to true in operator
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#1323 CI: Add filter for virtualization testing.
  Makefile
  docs/developer/testing/TESTING.md
  tests/e2e/e2e_suite_test.go
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm

#1296 OADP-3379: fix wrong descriptions on time fields
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/velero_test.go
  pkg/velero/server/config.go
Labels: approved, lgtm, jira/valid-reference

#1325 CI: Avoid DPA cleanup error on virt-only AfterSuite.
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm

#1313 OADP-2866: change snapshotMoveData to defaultSnapshotMoveData
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/velero.go
  controllers/velero_test.go
Labels: approved, lgtm, jira/valid-reference

#1304 OADP-3055: Add more keywords, categories and change maintainers to group e-mail
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#1314 OADP-3486: Fix garbage collection frequency description
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  pkg/velero/server/config.go
Labels: approved, lgtm, jira/valid-reference

#1330 CI: Add a minimal virtual machine startup/teardown test.
  tests/e2e/lib/virt_helpers.go
  tests/e2e/lib/virt_storage_helpers.go
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm, CI

#1332 Update OWNERS, to allow prow override
  OWNERS
Labels: approved, lgtm

#1269 OADP-3229: must-gather collect CRDs
  must-gather/Dockerfile
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_crds
  must-gather/collection-scripts/gather_crs
  must-gather/collection-scripts/gather_logs_without_zip
Labels: approved, lgtm, jira/valid-reference

#1274 OADP-3189: do not remove labels from OADP namespace
  Makefile
  main.go
  main_test.go
Labels: approved, lgtm, jira/valid-reference

#1338 [cherry-pick OADP 1.3]OADP-2866: change snapshotMoveData to defaultSnapshotMoveData (#1313)
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/velero.go
  controllers/velero_test.go
Labels: approved, lgtm, jira/valid-reference

#1214 OADP-3038: correct error when region cannot be auto discovered by velero
  controllers/bsl.go
  controllers/bsl_test.go
  pkg/storage/aws/s3.go
  pkg/storage/aws/s3_test.go
  tests/e2e/dpa_deployment_suite_test.go
Labels: approved, lgtm, jira/valid-reference

#1264 Fix OADP-3228: Controller Manager lease duration too short for SNO
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  go.mod
  main.go
  pkg/leaderelection/leaderelection.go
Labels: approved, lgtm, jira/valid-reference

#1344 [oadp-1.3] Fix OADP-3228: Controller Manager lease duration too short for SNO (#1264)
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  go.mod
  main.go
  pkg/leaderelection/leaderelection.go
Labels: approved, lgtm, jira/valid-reference

#1347 OADP-3586: Master: Update to ubi9 builder and base images
  Dockerfile
  must-gather/Dockerfile
Labels: approved, lgtm, jira/valid-reference

#1337 feat: Add golangci-lint linters - imports
  .golangci.yaml
  Makefile
  api/v1alpha1/oadp_types.go
  controllers/bsl.go
  controllers/bsl_test.go
  controllers/bucket_controller.go
  controllers/common.go
  controllers/dpa_controller.go
  controllers/monitor.go
  controllers/monitor_test.go
  controllers/nodeagent.go
  controllers/nodeagent_test.go
  controllers/predicate.go
  controllers/registry.go
  controllers/registry_test.go
  controllers/restore_resource_version_priority.go
  controllers/suite_test.go
  controllers/validator.go
  controllers/validator_test.go
  controllers/velero.go
  controllers/velero_test.go
  controllers/vsl.go
  controllers/vsl_test.go
  main.go
  main_test.go
  pkg/bucket/aws.go
  pkg/bucket/client.go
  pkg/credentials/credentials.go
  pkg/credentials/credentials_test.go
  pkg/leaderelection/leaderelection.go
  pkg/storage/aws/s3.go
  pkg/velero/server/args.go
  pkg/velero/server/config.go
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/lib/apps.go
  tests/e2e/lib/common_helpers.go
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/lib/nodeagent_helpers.go
  tests/e2e/lib/plugins_helpers.go
  tests/e2e/lib/velero_helpers.go
  tests/e2e/lib/virt_helpers.go
  tests/e2e/lib/virt_storage_helpers.go
  tests/e2e/must-gather_suite_test.go
  tests/e2e/subscription_suite_test.go
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm
