Repository openshift/oadp-operator, pull requests merged in 2024-05, with the labels that each got.

#1350 feat: Add PR template to project
  .github/pull_request_template.md
Labels: approved, lgtm

#1393 Handle NAC feature enablement via OADP for tech preview and GA scenarios
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/nonadmin_controller.go
  controllers/nonadmin_controller_test.go
  controllers/validator.go
  controllers/validator_test.go
Labels: approved, lgtm

#1275 fix: Add old datamover fields back to DPA
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/validator.go
Labels: approved, lgtm

#1394 fix: Delete unused files in E2E folder
  tests/e2e/sample-applications/block-pv/Dockerfile
  tests/e2e/sample-applications/block-pv/notes.txt
  tests/e2e/sample-applications/block-pv/pod.yaml
  tests/e2e/sample-applications/block-pv/pv.yaml
  tests/e2e/sample-applications/block-pv/pvc.yaml
  tests/e2e/sample-applications/deprecated/mssql-persistent/mssql-persistent-csi-template.yaml
  tests/e2e/sample-applications/deprecated/mssql-persistent/mssql-persistent-template.yaml
  tests/e2e/sample-applications/deprecated/parks-app/manifest.yaml
  tests/e2e/sample-applications/deprecated/parks-app/manifest4.8.yaml
Labels: approved, lgtm

#1392 Fix OADP-3960: Split labels avoiding label key exceed allowed 63 chars
  controllers/bsl.go
  controllers/dpa_controller.go
  docs/design/watches.md
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#1398 OADP-4137: updated for velero 1.14
  Dockerfile
  Makefile
  README.md
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  build/Dockerfile.bundle
  bundle.Dockerfile
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_cloudstorages.yaml
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  bundle/manifests/velero.io_backuprepositories.yaml
  bundle/manifests/velero.io_backups.yaml
  bundle/manifests/velero.io_backupstoragelocations.yaml
  bundle/manifests/velero.io_datadownloads.yaml
  bundle/manifests/velero.io_datauploads.yaml
  bundle/manifests/velero.io_deletebackuprequests.yaml
  bundle/manifests/velero.io_downloadrequests.yaml
  bundle/manifests/velero.io_podvolumebackups.yaml
  bundle/manifests/velero.io_podvolumerestores.yaml
  bundle/manifests/velero.io_restores.yaml
  bundle/manifests/velero.io_schedules.yaml
  bundle/manifests/velero.io_serverstatusrequests.yaml
  bundle/manifests/velero.io_volumesnapshotlocations.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/oadp.openshift.io_cloudstorages.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/velero.io_backuprepositories.yaml
  config/crd/bases/velero.io_backups.yaml
  config/crd/bases/velero.io_backupstoragelocations.yaml
  config/crd/bases/velero.io_datadownloads.yaml
  config/crd/bases/velero.io_datauploads.yaml
  config/crd/bases/velero.io_deletebackuprequests.yaml
  config/crd/bases/velero.io_downloadrequests.yaml
  config/crd/bases/velero.io_podvolumebackups.yaml
  config/crd/bases/velero.io_podvolumerestores.yaml
  config/crd/bases/velero.io_restores.yaml
  config/crd/bases/velero.io_schedules.yaml
  config/crd/bases/velero.io_serverstatusrequests.yaml
  config/crd/bases/velero.io_volumesnapshotlocations.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
  controllers/bucket_controller.go
  controllers/dpa_controller.go
  controllers/velero_test.go
  go.mod
  go.sum
  main.go
  pkg/common/common.go
  pkg/credentials/credentials.go
  pkg/credentials/credentials_test.go
  pkg/klog/zz_generated.deepcopy.go
  pkg/leaderelection/leaderelection.go
  pkg/velero/client/zz_generated.deepcopy.go
  pkg/velero/server/zz_generated.deepcopy.go
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/lib/restore.go
  tests/e2e/lib/velero_helpers.go
  tests/e2e/subscription_suite_test.go
Labels: approved, lgtm, jira/valid-reference

#1403 [oadp-1.4] remove restartPolicy for OCP 4.16
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent-block.yaml
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent-csi.yaml
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent.yaml
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent-csi.yaml
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent-twovol-csi.yaml
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent.yaml
Labels: approved, lgtm
