Repository openshift/oadp-operator, pull requests merged in 2024-01, with the labels that each got.

#1262 Must-gather, Store PIDs of all the subprocesses
  must-gather/collection-scripts/gather
Labels: approved, lgtm, ok-to-test

#1273 Use pre-built containers for the Mongo Sample app
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent-block.yaml
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent-csi.yaml
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent.yaml
Labels: approved, lgtm

#1271 Use full URI as the mongodb container image path.
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent-block.yaml
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent-csi.yaml
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent.yaml
Labels: approved, lgtm

#1279 velero dep update for 1.12.3 rebase
  controllers/nodeagent_test.go
  go.mod
  go.sum
Labels: approved

#1280 OADP-2866: Add DPA support for default-volumes-to-fs-backup and snapshot-move-data
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/velero.go
  controllers/velero_test.go
Labels: approved, lgtm, jira/valid-reference

#1277 Add flake attempts to the flaky tests and include known flakes pattern detection
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/lib/apps.go
  tests/e2e/lib/flakes.go
  tests/e2e/lib/velero_helpers.go
  tests/e2e/must-gather_suite_test.go
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent-block.yaml
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent-csi.yaml
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent.yaml
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent-csi.yaml
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent-twovol-csi.yaml
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent.yaml
Labels: approved, CI

#1272 Use more reliable way for checking if DB is alive from sample app.
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent-block.yaml
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent-csi.yaml
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent.yaml
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent-csi.yaml
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent-twovol-csi.yaml
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent.yaml
Labels: lgtm, CI

#1268 OADP-3165: Update default restore resource priorities
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/velero_test.go
  pkg/common/common.go
  pkg/velero/server/config.go
Labels: approved, lgtm, jira/valid-reference

#1267 fix: Remove unused field from e2e config
  Makefile
  tests/e2e/scripts/aws_settings.sh
  tests/e2e/scripts/azure_settings.sh
  tests/e2e/scripts/gcp_settings.sh
  tests/e2e/scripts/ibmcloud_settings.sh
  tests/e2e/templates/default_settings.json
Labels: approved, CI

#1216 Fix DPA reconcile on empty BSL secret name and key
  controllers/validator.go
  controllers/validator_test.go
Labels: approved, lgtm, ok-to-test

#1291 OADP-3041: Update fs-backup-timeout in DPA args to match velero
  api/v1alpha1/oadp_types.go
  controllers/velero.go
  controllers/velero_test.go
Labels: approved, lgtm, jira/valid-reference

#1257 CI: install virtualization operator to enable VM backup/restore testing
  Makefile
  docs/developer/testing/TESTING.md
  tests/e2e/e2e_suite_test.go
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/lib/subscription_helpers.go
  tests/e2e/lib/virt_helpers.go
  tests/e2e/subscription_suite_test.go
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm, CI

#1290 OADP-3395: Unbreak unsupportedOverrides field in DPA
  api/v1alpha1/oadp_types.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  tests/e2e/dpa_deployment_suite_test.go
Labels: approved, lgtm, jira/valid-reference

#1289 OADP-3326: Add DPA support for disable-informer-cache velero config flag
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/velero.go
  controllers/velero_test.go
Labels: approved, lgtm, jira/valid-reference
