Repository openshift/oadp-operator, pull requests merged in 2024-10, with the labels that each got.

#1374 fix: CI check go dependencies
  Makefile
Labels: approved, lgtm, CI

#1526 Allow developer to specify e2e test name on cli
  Makefile
  docs/developer/testing/TESTING.md
Labels: approved, lgtm

#1521 delete the existing backuprepositories prior to a new test
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/lib/backup.go
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm

#1529 OADP-3562: Fix controller panic on secret key-value parsing
  .golangci.yaml
  controllers/registry.go
Labels: approved, lgtm, jira/valid-reference

#1535 fix: Velero server args organization
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/velero.go
  controllers/velero_test.go
  go.mod
  go.sum
  pkg/klog/klog.go
  pkg/klog/zz_generated.deepcopy.go
  pkg/velero/client/config.go
  pkg/velero/client/zz_generated.deepcopy.go
  pkg/velero/server/args.go
  pkg/velero/server/config.go
  pkg/velero/server/zz_generated.deepcopy.go
Labels: approved, lgtm

#1545 cherry-pick : oadp-1.4: Add support for VSL name and labels (#1523)
  api/v1alpha1/oadp_types.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/vsl.go
Labels: approved, lgtm

#1544 cherry-pick: oadp-1.3: Add support for VSL name and labels (#1523)
  api/v1alpha1/oadp_types.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/vsl.go
Labels: approved, lgtm

#1546 fix: Update NAC CRDs
  bundle/manifests/nac.oadp.openshift.io_nonadminbackups.yaml
  config/crd/bases/nac.oadp.openshift.io_nonadminbackups.yaml
Labels: approved, lgtm

#1550 cherry-pick: oadp-1.3: OADP-3562: Fix controller panic on secret key-value parsing (#1529)
  controllers/registry.go
Labels: approved, lgtm, jira/valid-reference

#1549 OADP-3562: Fix controller panic on secret key-value parsing (#1529)
  controllers/registry.go
Labels: approved, lgtm, jira/valid-reference

#1548 cherry-pick: oadp-1.4: OADP-3050: Remove unwanted BSL/VSLs on create/edit DPA (#1525)
  controllers/bsl.go
  controllers/vsl.go
  tests/e2e/dpa_deployment_suite_test.go
Labels: approved, lgtm, jira/valid-reference

#1547 cherry-pick: oadp-1.3: OADP-3050: Remove unwanted BSL/VSLs on create/edit DPA
  controllers/bsl.go
  controllers/vsl.go
  pkg/common/common.go
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/lib/dpa_helpers.go
Labels: approved, lgtm, jira/valid-reference

#1541 Set unsupported images via shell in our e2e tests
  docs/developer/testing/TESTING.md
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/scripts/aws_settings.sh
  tests/e2e/scripts/azure_settings.sh
  tests/e2e/scripts/gcp_settings.sh
  tests/e2e/scripts/ibmcloud_settings.sh
  tests/e2e/scripts/openstack_settings.sh
Labels: approved, lgtm

#1551 Add 4.17, 4.18 badges
  README.md
Labels: approved, lgtm

#1539 OADP-4935: Default permission for Secrets
  controllers/common.go
  controllers/velero.go
  controllers/velero_test.go
  pkg/common/common.go
Labels: approved, lgtm, jira/valid-reference

#1554 [oadp-1.3] OADP-4935: Default permission for Secrets
  controllers/common.go
  controllers/velero.go
  controllers/velero_test.go
  pkg/common/common.go
Labels: approved, lgtm, jira/valid-reference

#1560 fix: Add images job badges to README
  README.md
Labels: approved, lgtm

#1562 fix: Add table for badges in README
  README.md
Labels: approved, lgtm

#1316 fix #1128: Removed multiple DPA get calls for Reconcilers
  controllers/bsl.go
  controllers/bsl_test.go
  controllers/dpa_controller.go
  controllers/monitor.go
  controllers/monitor_test.go
  controllers/nodeagent.go
  controllers/nodeagent_test.go
  controllers/nonadmin_controller.go
  controllers/nonadmin_controller_test.go
  controllers/registry.go
  controllers/restore_resource_version_priority.go
  controllers/validator.go
  controllers/validator_test.go
  controllers/velero.go
  controllers/velero_test.go
  controllers/vsl.go
  controllers/vsl_test.go
Labels: approved, lgtm

#1559 fix OADP-5044 and other VSL validation errors
  controllers/validator_test.go
  controllers/vsl.go
  controllers/vsl_test.go
Labels: approved, lgtm

#1561 [oadp-1.4] OADP-5072: Default permission for Secrets
  controllers/common.go
  controllers/velero.go
  controllers/velero_test.go
  pkg/common/common.go
Labels: approved, lgtm, jira/valid-reference

#1552 fix issue #1464: Added VSL Backup/Restore Tests
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/lib/dpa_helpers.go
Labels: approved, lgtm

#1556 CI: Enable upstream virtualization operator E2E tests.
  Makefile
  tests/e2e/e2e_suite_test.go
  tests/e2e/lib/subscription_helpers.go
  tests/e2e/lib/virt_helpers.go
  tests/e2e/lib/virt_storage_helpers.go
  tests/e2e/sample-applications/virtual-machines/cirros-test/cirros-rbac.yaml
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm

#1565 OADP-5079 Add support for legacy aws plugin
  README.md
  api/v1alpha1/oadp_types.go
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  config/manager/manager.yaml
  controllers/bsl.go
  controllers/validator.go
  controllers/validator_test.go
  controllers/velero.go
  controllers/velero_test.go
  controllers/vsl.go
  docs/config/plugins.md
  docs/developer/PROW_CI.md
  hack/disconnected-prep.sh
  pkg/common/common.go
  pkg/credentials/credentials.go
  pkg/credentials/credentials_test.go
Labels: approved, lgtm

#1570 [oadp-1.4] OADP-4995: Add support for legacy aws plugin
  api/v1alpha1/oadp_types.go
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  config/manager/manager.yaml
  controllers/bsl.go
  controllers/validator.go
  controllers/validator_test.go
  controllers/velero.go
  controllers/velero_test.go
  controllers/vsl.go
  deploy/disconnected-prep.sh
  docs/config/plugins.md
  pkg/common/common.go
  pkg/credentials/credentials.go
  pkg/credentials/credentials_test.go
Labels: approved, lgtm, jira/valid-reference

#1568 OADP-5106: Add legacy-aws default plugin reconcile e2e test.
  tests/e2e/dpa_deployment_suite_test.go
Labels: approved, lgtm, jira/valid-reference

#1573 oadp-1.4: Add legacy-aws default plugin reconcile e2e test. (#1568)
  tests/e2e/dpa_deployment_suite_test.go
Labels: approved, lgtm

#1543 convert the troubleshotting.md to proper md
  docs/TROUBLESHOOTING.md
Labels: approved, lgtm

#1574 OADP-5024 Virtualization troubleshooting document.
  docs/virtualization_troubleshooting.md
Labels: approved, lgtm

#1575 add virtualization debug to troubleshooting doc
  docs/TROUBLESHOOTING.md
Labels: approved, lgtm
