Repository openshift/oadp-operator, pull requests merged in 2024-03, with the labels that each got.

#1346 [oadp-1.3] OADP-3586: Update to ubi9 builder and base images
  Dockerfile
  must-gather/Dockerfile
Labels: approved, lgtm, jira/valid-reference

#1345 CI: Split up E2E test's runBackupAndRestore in preparation for virtualization tests.
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/must-gather_suite_test.go
Labels: approved, lgtm

#1333 CI: Back up and restore a VM.
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/lib/backup.go
  tests/e2e/lib/k8s_common_helpers.go
  tests/e2e/lib/restore.go
  tests/e2e/lib/virt_helpers.go
  tests/e2e/lib/virt_storage_helpers.go
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm, CI

#1349 [oadp-1.3] crd and go.mod updates for velero 1.12.4
  bundle/manifests/velero.io_datadownloads.yaml
  bundle/manifests/velero.io_datauploads.yaml
  config/crd/bases/velero.io_datadownloads.yaml
  config/crd/bases/velero.io_datauploads.yaml
  go.mod
  go.sum
Labels: approved, lgtm

#1354 fix: E2E subscription test
  tests/e2e/subscription_suite_test.go
Labels: approved, lgtm

#1355 OADP-3564: update restic debug w/ link to restic doc
  docs/restic_troubleshooting.md
Labels: approved, lgtm, jira/valid-reference

#1356 [oadp-1.3] fix: E2E subscription test (#1354)
  tests/e2e/subscription_suite_test.go
Labels: approved, lgtm

#1287 fix: Better description to wait for two vol test
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/lib/backup.go
  tests/e2e/lib/restore.go
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm, CI

#1246 fix: Remove and relocate files
  .dockerignore
  .github/workflows/docs-actions.yml
  .github/workflows/go-tests.yml
  .travis.yml
  OWNERS_ALIASES
  build/Dockerfile-ansible
  build/custom-ci-Dockerfile
  docs/design/upstream-datamover.md
  docs/developer/MTC_OADP_Upgrade.md
  hack/disconnected-prep.sh
Labels: approved, lgtm

#1358 fix: Unbreak must-gather Dockerfile
  must-gather/Dockerfile
Labels: approved, lgtm

#1359 OADP-2982: Test VMs from YAML templates
  tests/e2e/lib/virt_helpers.go
  tests/e2e/lib/virt_storage_helpers.go
  tests/e2e/sample-applications/virtual-machines/cirros-test/cirros-test-disk.yaml
  tests/e2e/sample-applications/virtual-machines/cirros-test/cirros-test-vm.yaml
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm, CI, jira/valid-reference

#1367 [oadp-1.3] OADP-3652: fix CVE CVE-2024-24786
  go.mod
  go.sum
Labels: approved, lgtm, jira/valid-reference

#1365 update mysql/mongo/other for 4.15 error on restartPolicy
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent-block.yaml
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent-csi.yaml
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent.yaml
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent-csi.yaml
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent-twovol-csi.yaml
  tests/e2e/sample-applications/mysql-persistent/mysql-persistent.yaml
Labels: approved, lgtm

#1366 OADP-3652: fix CVE CVE-2024-24786
  go.mod
  go.sum
Labels: approved, lgtm, jira/valid-reference

#1373 [oadp-1.3] fix: run `go mod tidy`
  go.sum
Labels: approved, lgtm

#1375 fix: CI unit test (envtest version)
  Makefile
Labels: approved, lgtm, CI
