Repository openshift/oadp-operator, pull requests merged in 2024-04, with the labels that each got.

#1378 fix: update PROW CI links: NAC
  docs/developer/PROW_CI.md
Labels: approved, lgtm

#1377 OADP-3821: Update restore order for cluster resources of ACM
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  controllers/velero_test.go
  pkg/common/common.go
  pkg/velero/server/config.go
Labels: approved, lgtm, jira/valid-reference

#1381 CI: Add fedora-todolist sample to E2E tests.
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/lib/virt_helpers.go
  tests/e2e/must-gather_suite_test.go
  tests/e2e/sample-applications/virtual-machines/fedora-todolist/fedora-todolist.yaml
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm, CI

#1370 feat: Integrate Non-Admin Controller (NAC) with OADP
  Makefile
  api/v1alpha1/oadp_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/nac.oadp.openshift.io_nonadminbackups.yaml
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/nac.oadp.openshift.io_nonadminbackups.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/non-admin-controller_rbac/kustomization.yaml
  config/non-admin-controller_rbac/role.yaml
  config/non-admin-controller_rbac/role_binding.yaml
  config/non-admin-controller_rbac/service_account.yaml
  config/samples/kustomization.yaml
  config/samples/nac_v1alpha1_nonadminbackup.yaml
  controllers/dpa_controller.go
  controllers/nonadmin_controller.go
  controllers/nonadmin_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
  pkg/common/common.go
  tests/e2e/lib/dpa_helpers.go
Labels: approved, lgtm

#1387 Update README.md velero version matrix for OADP 1.3.1
  README.md
Labels: approved, lgtm

#1386 CI: Convert CirrOS test to YAML.
  tests/e2e/lib/virt_helpers.go
  tests/e2e/lib/virt_storage_helpers.go
  tests/e2e/sample-applications/virtual-machines/cirros-test/cirros-test-disk.yaml
  tests/e2e/sample-applications/virtual-machines/cirros-test/cirros-test-vm.yaml
  tests/e2e/sample-applications/virtual-machines/cirros-test/cirros-test.yaml
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm, CI

#1385 [oadp-1.2] fix CI unit tests
  Makefile
Labels: approved, lgtm
