Repository openshift/oadp-operator, pull requests merged in 2025-08, with the labels that each got.

#1804 Upgrade operator-sdk from v1.34.2 to v1.35.0
  Makefile
  build/Dockerfile.bundle
  bundle.Dockerfile
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  docs/developer/update_operator_sdk.md
Labels: approved, lgtm

#1861 Nuke HCP, patch vs update and log
  tests/e2e/lib/hcp/hcp.go
Labels: approved, lgtm

#1773 Issue 1743: move/dupe podAnnotations into podConfig
  api/v1alpha1/dataprotectionapplication_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  internal/controller/nodeagent.go
  internal/controller/nodeagent_test.go
  internal/controller/velero.go
  internal/controller/velero_test.go
Labels: approved, lgtm, ok-to-test

#1892 oadp-1.5: Update konflux references
  .tekton/oadp-bundle-oadp-1-5-pull-request.yaml
  .tekton/oadp-bundle-oadp-1-5-push.yaml
  .tekton/oadp-operator-oadp-1-5-pull-request.yaml
  .tekton/oadp-operator-oadp-1-5-push.yaml
Labels: approved, lgtm, konflux-urgent

#1891 oadp-1.4: Update konflux references
  .tekton/oadp-bundle-oadp-1-4-pull-request.yaml
  .tekton/oadp-bundle-oadp-1-4-push.yaml
  .tekton/oadp-operator-oadp-1-4-pull-request.yaml
  .tekton/oadp-operator-oadp-1-4-push.yaml
Labels: approved, lgtm, konflux-urgent

#1898 Design: Non-Admin Backport to OADP 1.4
  docs/design/nonadmin_backport.md
Labels: approved, lgtm

#1896 OADP-6168: Use proper ConfigMap for the repository maintenance job
  internal/controller/repository_maintenance.go
  internal/controller/repository_maintenance_test.go
Labels: approved, lgtm, jira/valid-reference

#1862 OADP-6235: Add CaCert support for DPT
  api/v1alpha1/dataprotectiontest_types.go
  bundle/manifests/oadp.openshift.io_dataprotectiontests.yaml
  config/crd/bases/oadp.openshift.io_dataprotectiontests.yaml
  internal/controller/dataprotectiontest_controller.go
  internal/controller/dataprotectiontest_controller_test.go
  internal/controller/tls_config.go
  pkg/cloudprovider/aws.go
Labels: approved, lgtm, jira/valid-reference

#1913 OADP-6300: Fix DPT Azure Authentication with Velero BSL Secret Format
  pkg/cloudprovider/azure.go
  pkg/cloudprovider/azure_test.go
Labels: approved, lgtm, jira/valid-reference

#1916 add var to kick HCP/Hypershift tests
  docs/developer/testing/TESTING.md
Labels: approved, lgtm

#1911 README.md: add 4.20 tests for oadp-dev
  README.md
Labels: approved, lgtm
