Repository openshift/oadp-operator, pull requests merged in 2025-10, with the labels that each got.

#1976 Fix oadp-dev CI for velero 1.17, no restic 1.6+lint #1963
  api/v1alpha1/dataprotectionapplication_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  bundle/manifests/velero.io_backuprepositories.yaml
  bundle/manifests/velero.io_backups.yaml
  bundle/manifests/velero.io_datauploads.yaml
  bundle/manifests/velero.io_podvolumebackups.yaml
  bundle/manifests/velero.io_podvolumerestores.yaml
  bundle/manifests/velero.io_schedules.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/velero.io_backuprepositories.yaml
  config/crd/bases/velero.io_backups.yaml
  config/crd/bases/velero.io_datauploads.yaml
  config/crd/bases/velero.io_podvolumebackups.yaml
  config/crd/bases/velero.io_podvolumerestores.yaml
  config/crd/bases/velero.io_schedules.yaml
  go.mod
  go.sum
  internal/controller/bsl_test.go
  internal/controller/cloudstorage_controller.go
  internal/controller/dataprotectiontest_controller.go
  internal/controller/nodeagent.go
  internal/controller/nodeagent_test.go
  internal/controller/nonadmin_controller_test.go
  internal/controller/validator.go
  internal/controller/validator_test.go
  internal/controller/velero.go
  internal/controller/vsl_test.go
  tests/e2e/backup_restore_cli_suite_test.go
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/hcp_backup_restore_suite_test.go
  tests/e2e/lib/apps.go
  tests/e2e/lib/common_helpers.go
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/lib/virt_helpers.go
  tests/e2e/lib/virt_storage_helpers.go
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent-block.yaml
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent-csi.yaml
  tests/e2e/sample-applications/mongo-persistent/mongo-persistent.yaml
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm

#1965 Add: operators.openshift.io/must-gather-image
  Makefile
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, konflux-urgent

#1961 Improve documentation for custom plugin images usage
  docs/config/custom_plugin_images.md
Labels: approved

#1979 Konflux: ART: Update currentCSV value
  bundle/oadp-operator.package.yaml
Labels: approved, lgtm, konflux-urgent

#1982 Konflux: ART: Add LABEL(s)
  konflux.Dockerfile
Labels: approved, lgtm, konflux-urgent

#1983 Konflux: ART: Add LABEL(s)
  konflux.Dockerfile
Labels: approved, lgtm, konflux-urgent
