Repository openshift/oadp-operator, pull requests merged in 2025-05, with the labels that each got.

#1739 use golang 1.23.x for 1.3
  must-gather/go.mod
Labels: approved, lgtm

#1742 remove mateusoliveira43
  OWNERS
Labels: approved, lgtm

#1741 Include screenshots in the oadp-must-gather readme
  must-gather/README.md
Labels: approved, lgtm

#1745 OADP-6085: exceptions for operators best practices
  docs/cluster_permissions_in_csv_exception.md
Labels: approved, jira/valid-reference

#1746 Add DPT to OADP must gather
  must-gather/go.mod
  must-gather/go.sum
  must-gather/pkg/cli.go
  must-gather/pkg/gvk/gvk.go
  must-gather/pkg/templates/summary.go
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/lib/dpt.go
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved

#1747 OADP-6105: Handle STS Cred in parseAWSSecret
  internal/controller/registry.go
  internal/controller/registry_test.go
Labels: do-not-merge/hold, approved, jira/valid-reference

#1626 add a 3 cirros-vm test for manual recreate
  tests/e2e/sample-applications/virtual-machines/cirros-test/3-vms/README.MD
  tests/e2e/sample-applications/virtual-machines/cirros-test/3-vms/cirros-test-with-dataVolumeContainer/RESULTS/cirros-test-cont-1-dv
  tests/e2e/sample-applications/virtual-machines/cirros-test/3-vms/cirros-test-with-dataVolumeContainer/RESULTS/describe-cirros-test-cont-1-dv
  tests/e2e/sample-applications/virtual-machines/cirros-test/3-vms/cirros-test-with-dataVolumeContainer/RESULTS/describe-vm-cirros-test-cont-1
  tests/e2e/sample-applications/virtual-machines/cirros-test/3-vms/cirros-test-with-dataVolumeContainer/RESULTS/restore-cirros-test-cont-1
  tests/e2e/sample-applications/virtual-machines/cirros-test/3-vms/cirros-test-with-dataVolumeContainer/RESULTS/restore-cirros-test-cont-1-get-all
  tests/e2e/sample-applications/virtual-machines/cirros-test/3-vms/cirros-test-with-dataVolumeContainer/RESULTS/visual_diff_of_restore.png
  tests/e2e/sample-applications/virtual-machines/cirros-test/3-vms/cirros-test-with-dataVolumeContainer/cirros-test-1.yaml
  tests/e2e/sample-applications/virtual-machines/cirros-test/3-vms/cirros-test-with-dataVolumeContainer/cirros-test-2.yaml
  tests/e2e/sample-applications/virtual-machines/cirros-test/3-vms/cirros-test-with-dataVolumeContainer/cirros-test-3.yaml
  tests/e2e/sample-applications/virtual-machines/cirros-test/3-vms/cirros-test-with-dataVolumePV/cirros-datasource-datavolume.yaml
  tests/e2e/sample-applications/virtual-machines/cirros-test/3-vms/cirros-test-with-dataVolumePV/cirros-test-1.yaml
  tests/e2e/sample-applications/virtual-machines/cirros-test/3-vms/cirros-test-with-dataVolumePV/cirros-test-2.yaml
  tests/e2e/sample-applications/virtual-machines/cirros-test/3-vms/cirros-test-with-dataVolumePV/cirros-test-3.yaml
  tests/e2e/sample-applications/virtual-machines/cirros-test/3-vms/cirros-test-with-dataVolumePV/restore-cirros-test-3-only.yaml
Labels: approved, lgtm

#1752 OADP-5275 init plugin containers to have read only fs
  internal/controller/velero.go
  internal/controller/velero_test.go
Labels: approved, lgtm

#1756 Velero 1.16.1 rebase
  go.mod
  go.sum
Labels: approved, lgtm

#1757 velero 1.16.1 rebase 2
  go.mod
  go.sum
Labels: approved, lgtm

#1730 Add user documentation for the node backupPVC and restorePVC
  docs/data_mover_backup_pvc_configuration.md
Labels: approved, lgtm

#1755 Fix velero container to have explicit ReadOnlyRootFilesystem
  internal/controller/velero.go
  internal/controller/velero_test.go
Labels: approved, lgtm

#1707 add kubevirt-velero-plugin mapping to velero/oadp
  PARTNERS.md
Labels: approved, lgtm

#1749 OADP-6121: E2E Add backup/restore coverage with kubevirt, hypershift plugins loaded.
  tests/e2e/scripts/aws_settings.sh
Labels: approved, lgtm, jira/valid-reference

#1763 add kubevirt, hypershift plugins to dpa
  tests/e2e/scripts/aws_settings.sh
Labels: approved, lgtm

#1764 Issue 1754: improve the documentation about OADP Monitoring
  docs/oadp_monitoring.md
Labels: approved, lgtm, ok-to-test

#1766 add hypershift periodic status
  README.md
Labels: approved, lgtm

#1769 allow user to skip must-gather
  Makefile
  docs/developer/testing/TESTING.md
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/e2e_suite_test.go
Labels: approved, lgtm
