Repository openshift/oadp-operator, pull requests merged in 2025-03, with the labels that each got.

#1649 fix: Show backup/restore progress in NAB/NAR status
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_nonadminbackups.yaml
  bundle/manifests/oadp.openshift.io_nonadminrestores.yaml
  config/crd/bases/oadp.openshift.io_nonadminbackups.yaml
  config/crd/bases/oadp.openshift.io_nonadminrestores.yaml
  config/non-admin-controller_rbac/role.yaml
Labels: approved, lgtm

#1576 first pass at a code of conduct
  CODE_OF_CONDUCT.md
Labels: approved, lgtm

#1643 NonAdminDownloadRequest API
  bundle/manifests/nonadmindownloadrequest-admin-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/nonadmindownloadrequest-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/nonadmindownloadrequest-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_nonadmindownloadrequests.yaml
  config/crd/bases/oadp.openshift.io_nonadmindownloadrequests.yaml
  config/crd/kustomization.yaml
  config/manager/manager.yaml
  config/non-admin-controller_rbac/kustomization.yaml
  config/non-admin-controller_rbac/nonadmindownloadrequest_admin_role.yaml
  config/non-admin-controller_rbac/nonadmindownloadrequest_editor_role.yaml
  config/non-admin-controller_rbac/nonadmindownloadrequest_viewer_role.yaml
  config/non-admin-controller_rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/oadp_v1alpha1_nonadmindownloadrequest.yaml
Labels: approved, lgtm

#1651 Fix for macOS `sed -i`
  Makefile
Labels: approved, lgtm

#1658 update path to store junit.xml file
  Makefile
Labels: approved, lgtm

#1235 OADP-5158: Do not allow restic config use in OADP 1.5+; Deprecate restic for file system backups
  api/v1alpha1/dataprotectionapplication_types.go
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  config/manager/manager.yaml
  config/samples/kustomization.yaml
  config/samples/oadp_v1alpha1_dataprotectionapplication.yaml
  config/samples/resticrepository.yaml
  internal/controller/nodeagent.go
  internal/controller/nodeagent_test.go
  internal/controller/validator.go
  internal/controller/validator_test.go
  internal/controller/velero.go
  pkg/credentials/credentials.go
  tests/e2e/dpa_deployment_suite_test.go
Labels: approved, lgtm, jira/valid-reference

#1650 update image for arm,amd manifest
  tests/e2e/sample-applications/minimal-8csivol/minimal-block-3csivol.yaml
Labels: approved, lgtm

#1657 Add the dataMoverPrepareTimeout and resourceTimeout to the Node-Agent
  api/v1alpha1/dataprotectionapplication_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  internal/controller/nodeagent.go
  internal/controller/nodeagent_test.go
Labels: approved, lgtm

#1662 OADP-5635: dpa support for parallel item backup
  api/v1alpha1/dataprotectionapplication_types.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  internal/controller/velero.go
  internal/controller/velero_test.go
Labels: approved, lgtm, jira/valid-reference

#1666 velero rebase Mar 13 2025
  Makefile
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_cloudstorages.yaml
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  bundle/manifests/velero.io_backuprepositories.yaml
  bundle/manifests/velero.io_backups.yaml
  bundle/manifests/velero.io_backupstoragelocations.yaml
  bundle/manifests/velero.io_datadownloads.yaml
  bundle/manifests/velero.io_datauploads.yaml
  bundle/manifests/velero.io_deletebackuprequests.yaml
  bundle/manifests/velero.io_downloadrequests.yaml
  bundle/manifests/velero.io_podvolumebackups.yaml
  bundle/manifests/velero.io_podvolumerestores.yaml
  bundle/manifests/velero.io_restores.yaml
  bundle/manifests/velero.io_schedules.yaml
  bundle/manifests/velero.io_serverstatusrequests.yaml
  bundle/manifests/velero.io_volumesnapshotlocations.yaml
  config/crd/bases/oadp.openshift.io_cloudstorages.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/velero.io_backuprepositories.yaml
  config/crd/bases/velero.io_backups.yaml
  config/crd/bases/velero.io_backupstoragelocations.yaml
  config/crd/bases/velero.io_datadownloads.yaml
  config/crd/bases/velero.io_datauploads.yaml
  config/crd/bases/velero.io_deletebackuprequests.yaml
  config/crd/bases/velero.io_downloadrequests.yaml
  config/crd/bases/velero.io_podvolumebackups.yaml
  config/crd/bases/velero.io_podvolumerestores.yaml
  config/crd/bases/velero.io_restores.yaml
  config/crd/bases/velero.io_schedules.yaml
  config/crd/bases/velero.io_serverstatusrequests.yaml
  config/crd/bases/velero.io_volumesnapshotlocations.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/dataprotectionapplication_controller.go
  internal/controller/nodeagent.go
  internal/controller/nodeagent_test.go
  internal/controller/velero.go
  internal/controller/velero_test.go
  tests/e2e/backup_restore_suite_test.go
Labels: approved, lgtm

#1669 CVE & CRD updates openshift/velero #371
  Dockerfile
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_cloudstorages.yaml
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  bundle/manifests/velero.io_backuprepositories.yaml
  bundle/manifests/velero.io_backups.yaml
  bundle/manifests/velero.io_backupstoragelocations.yaml
  bundle/manifests/velero.io_datadownloads.yaml
  bundle/manifests/velero.io_datauploads.yaml
  bundle/manifests/velero.io_deletebackuprequests.yaml
  bundle/manifests/velero.io_downloadrequests.yaml
  bundle/manifests/velero.io_podvolumebackups.yaml
  bundle/manifests/velero.io_podvolumerestores.yaml
  bundle/manifests/velero.io_restores.yaml
  bundle/manifests/velero.io_schedules.yaml
  bundle/manifests/velero.io_serverstatusrequests.yaml
  bundle/manifests/velero.io_volumesnapshotlocations.yaml
  config/crd/bases/oadp.openshift.io_cloudstorages.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/velero.io_backuprepositories.yaml
  config/crd/bases/velero.io_backups.yaml
  config/crd/bases/velero.io_backupstoragelocations.yaml
  config/crd/bases/velero.io_datadownloads.yaml
  config/crd/bases/velero.io_datauploads.yaml
  config/crd/bases/velero.io_deletebackuprequests.yaml
  config/crd/bases/velero.io_downloadrequests.yaml
  config/crd/bases/velero.io_podvolumebackups.yaml
  config/crd/bases/velero.io_podvolumerestores.yaml
  config/crd/bases/velero.io_restores.yaml
  config/crd/bases/velero.io_schedules.yaml
  config/crd/bases/velero.io_serverstatusrequests.yaml
  config/crd/bases/velero.io_volumesnapshotlocations.yaml
  go.mod
  go.sum
  must-gather/Dockerfile
  pkg/klog/zz_generated.deepcopy.go
  pkg/velero/client/zz_generated.deepcopy.go
  pkg/velero/server/zz_generated.deepcopy.go
Labels: approved, lgtm, tide/merge-method-squash

#1664 Add logFormat to the DPA's velero config
  api/v1alpha1/dataprotectionapplication_types.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  internal/controller/velero.go
  internal/controller/velero_test.go
  pkg/common/common_test.go
Labels: approved, lgtm

#1660 Fix for the node-agent privs and volumes
  api/v1alpha1/dataprotectionapplication_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  config/samples/oadp_v1alpha1_dataprotectionapplication.yaml
  internal/controller/nodeagent.go
  internal/controller/nodeagent_test.go
Labels: approved, lgtm

#1674 NO-JIRA: Fix for Improve DPA additionalPrinterColumns
  api/v1alpha1/dataprotectionapplication_types.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
Labels: approved, lgtm, jira/valid-reference

#1648 CRD updates for the oc CLI fields for the NAR, NAB and NABSL objects
  bundle/manifests/oadp.openshift.io_nonadminbackups.yaml
  bundle/manifests/oadp.openshift.io_nonadminbackupstoragelocationrequests.yaml
  bundle/manifests/oadp.openshift.io_nonadminbackupstoragelocations.yaml
  bundle/manifests/oadp.openshift.io_nonadmindownloadrequests.yaml
  bundle/manifests/oadp.openshift.io_nonadminrestores.yaml
  config/crd/bases/oadp.openshift.io_nonadminbackups.yaml
  config/crd/bases/oadp.openshift.io_nonadminbackupstoragelocationrequests.yaml
  config/crd/bases/oadp.openshift.io_nonadminbackupstoragelocations.yaml
  config/crd/bases/oadp.openshift.io_nonadmindownloadrequests.yaml
  config/crd/bases/oadp.openshift.io_nonadminrestores.yaml
Labels: approved, lgtm

#1678 controller-gen v0.16.5 nac manifests
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_nonadminbackups.yaml
  bundle/manifests/oadp.openshift.io_nonadminbackupstoragelocationrequests.yaml
  bundle/manifests/oadp.openshift.io_nonadminbackupstoragelocations.yaml
  bundle/manifests/oadp.openshift.io_nonadmindownloadrequests.yaml
  bundle/manifests/oadp.openshift.io_nonadminrestores.yaml
  config/crd/bases/oadp.openshift.io_nonadminbackups.yaml
  config/crd/bases/oadp.openshift.io_nonadminbackupstoragelocationrequests.yaml
  config/crd/bases/oadp.openshift.io_nonadminbackupstoragelocations.yaml
  config/crd/bases/oadp.openshift.io_nonadmindownloadrequests.yaml
  config/crd/bases/oadp.openshift.io_nonadminrestores.yaml
  config/non-admin-controller_rbac/role.yaml
Labels: approved, lgtm

#1670 OADP-5185, OADP-5187: exceptions for operators best practices #76, #90
  docs/container_lifecycle_hooks_exception.md
Labels: approved, lgtm, jira/valid-reference

#1667 Add option to use ConfigMap in the node agent
  api/v1alpha1/dataprotectionapplication_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  internal/controller/dataprotectionapplication_controller.go
  internal/controller/nodeagent.go
  internal/controller/nodeagent_test.go
  pkg/common/common.go
Labels: approved, lgtm

#1679 Ensure root fs in the controller manager is readonly
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm

#1680 OADP-5857: CVE-2025-30204
  go.mod
  go.sum
Labels: approved, lgtm, jira/valid-reference

#1682 fix: envtest version for OCP 4.19
  Makefile
  internal/controller/suite_test.go
Labels: approved, lgtm

#1676 OADP-5782: Add hypershift-oadp-plugin as a default one in oadp-operator
  .gitignore
  api/v1alpha1/dataprotectionapplication_types.go
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  config/manager/manager.yaml
  docs/developer/testing/TESTING.md
  go.mod
  go.sum
  internal/controller/nodeagent_test.go
  internal/controller/velero_test.go
  pkg/common/common.go
  pkg/credentials/credentials.go
  pkg/credentials/credentials_test.go
  tests/e2e/scripts/aws_settings.sh
  tests/e2e/scripts/azure_settings.sh
  tests/e2e/scripts/gcp_settings.sh
  tests/e2e/scripts/ibmcloud_settings.sh
  tests/e2e/scripts/openstack_settings.sh
  tests/e2e/templates/default_settings.json
Labels: approved, lgtm, jira/valid-reference

#1594 OADP future releases and versions
  PARTNERS.md
Labels: approved, lgtm, tide/merge-method-squash
