Repository openshift/oadp-operator, pull requests merged in 2025-02, with the labels that each got.

#1622 Remove multiple single quotes from message field
  internal/controller/validator.go
  internal/controller/validator_test.go
Labels: approved, lgtm

#1623 feat: Garbage collector input
  api/v1alpha1/dataprotectionapplication_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  internal/controller/nonadmin_controller.go
  internal/controller/validator.go
Labels: approved, lgtm

#1629 Adding --ginkgo.junit-report flag
  .gitignore
  Makefile
Labels: approved, lgtm, ok-to-test

#1630 Enable unparam flag in linter: Resolve unused func params
  .golangci.yaml
  internal/controller/bsl.go
  internal/controller/bsl_test.go
  internal/controller/monitor_test.go
  internal/controller/nodeagent.go
  internal/controller/nodeagent_test.go
  internal/controller/registry_test.go
  internal/controller/validator.go
  internal/controller/validator_test.go
  internal/controller/velero.go
  internal/controller/velero_test.go
  internal/controller/vsl.go
  internal/controller/vsl_test.go
  pkg/common/common.go
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/lib/k8s_common_helpers.go
  tests/e2e/must-gather_suite_test.go
  tests/e2e/upgrade_suite_test.go
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm, ok-to-test

#1631 Make common function for updating BSL spec
  api/v1alpha1/dataprotectionapplication_types.go
  internal/controller/bsl.go
  internal/controller/bsl_test.go
  internal/controller/registry.go
  pkg/common/common.go
  pkg/common/common_test.go
Labels: approved, lgtm

#1624 feat: NAC backup sync controller input
  api/v1alpha1/dataprotectionapplication_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  config/non-admin-controller_rbac/role.yaml
  internal/controller/nonadmin_controller.go
  internal/controller/nonadmin_controller_test.go
  internal/controller/suite_test.go
  internal/controller/validator.go
  internal/controller/validator_test.go
Labels: approved, lgtm

#1632 Restrict enforcing NAB spec that are restricted for non-admin users
  internal/controller/validator.go
  internal/controller/validator_test.go
Labels: approved, lgtm

#1636 fix: show velero backup spec in NonAdminBackup status
  bundle/manifests/oadp.openshift.io_nonadminbackups.yaml
  config/crd/bases/oadp.openshift.io_nonadminbackups.yaml
Labels: approved, lgtm

#1637 fix: restrict vsl enforcement
  internal/controller/validator.go
  internal/controller/validator_test.go
Labels: approved, lgtm

#1639 Restrict enforcing NAR spec that are restricted for non-admin users
  internal/controller/validator.go
  internal/controller/validator_test.go
Labels: approved, lgtm, feature complete

#1640 fix: NAC associated objects deletion
  bundle/manifests/oadp.openshift.io_nonadminbackups.yaml
  config/crd/bases/oadp.openshift.io_nonadminbackups.yaml
Labels: approved, lgtm

#1635 Pass LogLevel to NAC deployment
  .gitignore
  internal/controller/nonadmin_controller.go
  internal/controller/nonadmin_controller_test.go
  pkg/common/common.go
Labels: approved, lgtm

#1638 fix: BSL sync period validation with NAC
  internal/controller/nonadmin_controller.go
  internal/controller/nonadmin_controller_test.go
  internal/controller/validator.go
Labels: approved, lgtm

#1644 Update CRD and logic to enable Non Admin BSL enforcements
  api/v1alpha1/dataprotectionapplication_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  bundle/manifests/oadp.openshift.io_nonadminbackups.yaml
  bundle/manifests/oadp.openshift.io_nonadminbackupstoragelocationrequests.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_nonadminbackups.yaml
  config/crd/bases/oadp.openshift.io_nonadminbackupstoragelocationrequests.yaml
  internal/controller/nonadmin_controller_test.go
  internal/controller/validator.go
  internal/controller/validator_test.go
Labels: approved, lgtm

#1645 Adds missing NAC manifest change for the deleteBackup description
  bundle/manifests/oadp.openshift.io_nonadminbackups.yaml
  config/crd/bases/oadp.openshift.io_nonadminbackups.yaml
Labels: approved, lgtm

#1646 Fix dpa CRD manifest
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
Labels: approved, lgtm

#1654 Use intended version of opm operator-sdk
  Makefile
Labels: approved, lgtm
