Repository openshift/oadp-operator, pull requests merged in 2025-09, with the labels that each got.

#1921 Add HCP full backup/restore test suite for clusters with data plane
  Makefile
  docs/developer/testing/TESTING.md
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/hcp_backup_restore_suite_test.go
  tests/e2e/hcp_external_cluster_backup_restore_suite_test.go
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/lib/hcp/hcp.go
Labels: approved, lgtm

#1935 Update CSV for 1.5.1
  Makefile
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, konflux-urgent

#1940 oadp-1.5: Prepare for ART Konflux builds
  hack/build/redhat.repo
  hack/build/rpms.in.yaml
  hack/build/rpms.lock.yaml
  konflux.Dockerfile
  konflux.bundle.Dockerfile
  konflux/bundle/manifests/nonadmindownloadrequest-admin-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  konflux/bundle/manifests/nonadmindownloadrequest-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  konflux/bundle/manifests/nonadmindownloadrequest-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  konflux/bundle/manifests/oadp-operator.clusterserviceversion.yaml
  konflux/bundle/manifests/oadp.openshift.io_cloudstorages.yaml
  konflux/bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  konflux/bundle/manifests/oadp.openshift.io_dataprotectiontests.yaml
  konflux/bundle/manifests/oadp.openshift.io_nonadminbackups.yaml
  konflux/bundle/manifests/oadp.openshift.io_nonadminbackupstoragelocationrequests.yaml
  konflux/bundle/manifests/oadp.openshift.io_nonadminbackupstoragelocations.yaml
  konflux/bundle/manifests/oadp.openshift.io_nonadmindownloadrequests.yaml
  konflux/bundle/manifests/oadp.openshift.io_nonadminrestores.yaml
  konflux/bundle/manifests/openshift-adp-controller-manager-metrics-service_v1_service.yaml
  konflux/bundle/manifests/openshift-adp-dataprotectiontest-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  konflux/bundle/manifests/openshift-adp-dataprotectiontest-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  konflux/bundle/manifests/openshift-adp-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  konflux/bundle/manifests/velero.io_backuprepositories.yaml
  konflux/bundle/manifests/velero.io_backups.yaml
  konflux/bundle/manifests/velero.io_backupstoragelocations.yaml
  konflux/bundle/manifests/velero.io_datadownloads.yaml
  konflux/bundle/manifests/velero.io_datauploads.yaml
  konflux/bundle/manifests/velero.io_deletebackuprequests.yaml
  konflux/bundle/manifests/velero.io_downloadrequests.yaml
  konflux/bundle/manifests/velero.io_podvolumebackups.yaml
  konflux/bundle/manifests/velero.io_podvolumerestores.yaml
  konflux/bundle/manifests/velero.io_restores.yaml
  konflux/bundle/manifests/velero.io_schedules.yaml
  konflux/bundle/manifests/velero.io_serverstatusrequests.yaml
  konflux/bundle/manifests/velero.io_volumesnapshotlocations.yaml
  konflux/bundle/metadata/annotations.yaml
  konflux/bundle/tests/scorecard/config.yaml
Labels: approved, lgtm, konflux-urgent

#1941 Add performance testing documentation and repository reference
  README.md
  docs/performance_testing.md
Labels: approved

#1936 OADP-6652: Fix unnecessary secret updates and logging in STS flow
  internal/controller/bsl_test.go
  internal/controller/cloudstorage_controller.go
  pkg/bucket/azure.go
  pkg/bucket/azure_test.go
  pkg/credentials/stsflow/stsflow.go
  pkg/credentials/stsflow/stsflow_test.go
Labels: approved, lgtm, jira/valid-reference

#1937 OADP-6653: CloudStorage exponential backoff by removing RequeueAfter
  api/v1alpha1/cloudstorage_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_cloudstorages.yaml
  config/crd/bases/oadp.openshift.io_cloudstorages.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
  internal/controller/cloudstorage_controller.go
  internal/controller/cloudstorage_controller_test.go
  internal/controller/mock_bucket_client_test.go
Labels: approved, lgtm, jira/valid-reference

#1942 OADP-6669: Use CloudStorage creationSecret and config as fallback for BSL
  internal/controller/bsl.go
  internal/controller/bsl_test.go
  internal/controller/cloudstorage_providers_integration_test.go
  internal/controller/registry.go
  internal/controller/registry_test.go
  internal/controller/validator_test.go
Labels: approved, lgtm, jira/valid-reference

#1953 update QE_PROW.md with azure runs information
  QE_PROW.md
Labels: approved, lgtm

#1955 Konflux: Add art.yaml and image-references
  bundle/art.yaml
  bundle/image-references
Labels: approved, lgtm, konflux-urgent

#1962 Konflux: 1.5: ART updates
  bundle/art.yaml
  bundle/image-references
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, konflux-urgent

#1966 Konflux: 1.4: ART updates
  bundle/art.yaml
  bundle/image-references
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
Labels: approved, lgtm, konflux-urgent
