Repository openshift/oadp-operator, pull requests merged in 2025-04, with the labels that each got.

#1686 prow: check more locally before submit
  docs/developer/PROW_CI.md
Labels: approved, lgtm

#1671 fix: OADP must-gather refactor
  .gitignore
  must-gather/Dockerfile
  must-gather/Makefile
  must-gather/README.md
  must-gather/cmd/main.go
  must-gather/collection-scripts/_metrics_chart_template_part_1.html
  must-gather/collection-scripts/_metrics_chart_template_part_2.html
  must-gather/collection-scripts/debug/tail_failed_pods
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_crds
  must-gather/collection-scripts/gather_crs
  must-gather/collection-scripts/gather_logs
  must-gather/collection-scripts/gather_logs_without_zip
  must-gather/collection-scripts/gather_metrics
  must-gather/collection-scripts/gather_metrics_dump
  must-gather/collection-scripts/gather_versions
  must-gather/collection-scripts/gather_without_tls
  must-gather/collection-scripts/logs/gather_logs_backup
  must-gather/collection-scripts/logs/gather_logs_pods
  must-gather/collection-scripts/logs/gather_logs_pvb
  must-gather/collection-scripts/logs/gather_logs_pvr
  must-gather/collection-scripts/logs/gather_logs_restore
  must-gather/collection-scripts/pwait
  must-gather/collection-scripts/time_window_gather/gather_1h
  must-gather/collection-scripts/time_window_gather/gather_1h_essential
  must-gather/collection-scripts/time_window_gather/gather_24h
  must-gather/collection-scripts/time_window_gather/gather_24h_essential
  must-gather/collection-scripts/time_window_gather/gather_6h
  must-gather/collection-scripts/time_window_gather/gather_6h_essential
  must-gather/collection-scripts/time_window_gather/gather_72h
  must-gather/collection-scripts/time_window_gather/gather_72h_essential
  must-gather/collection-scripts/time_window_gather/gather_all
  must-gather/collection-scripts/time_window_gather/gather_all_essential
  must-gather/collection-scripts/time_window_gather/gather_with_timeout
  must-gather/go.mod
  must-gather/go.sum
  must-gather/pkg/cli.go
  must-gather/pkg/gather/gather.go
  must-gather/pkg/gvk/gvk.go
  must-gather/pkg/templates/summary.go
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/lib/apps.go
  tests/e2e/must-gather_suite_test.go
Labels: approved, lgtm

#1689 Updating image tags for oadp-1.5 branch
  Makefile
  README.md
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1691 OADP-5858: CVE-2025-30204
  go.mod
  go.sum
Labels: approved, lgtm, jira/valid-reference

#1687 OADP-5799: Pass log format to NAC controller
  internal/controller/nonadmin_controller.go
  internal/controller/nonadmin_controller_test.go
  pkg/common/common.go
Labels: approved, lgtm, jira/valid-reference

#1693 Fix multiple CVE's
  go.mod
  go.sum
Labels: approved, lgtm

#1672 OADP-5179: Validate secret content in validator for parsing errors
  internal/controller/bsl.go
  internal/controller/bsl_test.go
  internal/controller/registry.go
  internal/controller/validator_test.go
Labels: approved, lgtm, jira/valid-reference

#1695 remove velero-restore-helper image
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  docs/developer/PROW_CI.md
  hack/disconnected-prep.sh
  internal/controller/nodeagent.go
  internal/controller/nodeagent_test.go
Labels: approved, lgtm

#1696 [oadp 1.5] remove velero-restore-helper image
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  docs/developer/PROW_CI.md
  hack/disconnected-prep.sh
  internal/controller/nodeagent.go
  internal/controller/nodeagent_test.go
Labels: approved, lgtm

#1677 OADP-5735: validate upgrade to 1.5
  docs/upgrade_1-4_to_1-5.md
  tests/e2e/upgrade_suite_test.go
Labels: approved, lgtm, jira/valid-reference

#1698 fix: NAC CI
  config/manager/manager.yaml
Labels: approved, lgtm

#1704 [oadp-1.5] fix: NAC CI
  Makefile
  config/manager/manager.yaml
Labels: approved, lgtm

#1708 [oadp-1.5] fix: cherry-pick leftover
  must-gather/Dockerfile
  must-gather/pkg/cli.go
  tests/e2e/upgrade_suite_test.go
Labels: approved, lgtm

#1705 OADP-5900: DPA config for backup repo cache and full maintenance interval
  api/v1alpha1/dataprotectionapplication_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  go.mod
  internal/controller/backup_repository.go
  internal/controller/backup_repository_test.go
  internal/controller/dataprotectionapplication_controller.go
  internal/controller/velero.go
  internal/controller/velero_test.go
  pkg/common/common.go
Labels: approved, lgtm, jira/valid-reference

#1683 Node Selector Configuration for Data Protection Components - NodeAgent and DataMover
  api/v1alpha1/dataprotectionapplication_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  docs/design/DPA-and-node-selectors.md
  internal/controller/nodeagent.go
  internal/controller/nodeagent_test.go
  internal/controller/validator.go
  internal/controller/validator_test.go
Labels: approved, lgtm

#1710 [oadp-1.5] DPA config for backup repo cache and full maintenance interval (#1705)
  api/v1alpha1/dataprotectionapplication_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  go.mod
  internal/controller/backup_repository.go
  internal/controller/backup_repository_test.go
  internal/controller/dataprotectionapplication_controller.go
  internal/controller/velero.go
  internal/controller/velero_test.go
  pkg/common/common.go
Labels: approved, lgtm

#1706 OADP-5901: Add design for DataProtectionTest CRD and Controller
  docs/design/data-protection-test.md
Labels: approved, lgtm, jira/valid-reference

#1688 Oadp repository maintenance Config Map with affinity settings
  api/v1alpha1/dataprotectionapplication_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp.openshift.io_dataprotectionapplications.yaml
  config/crd/bases/oadp.openshift.io_dataprotectionapplications.yaml
  internal/controller/dataprotectionapplication_controller.go
  internal/controller/repository_maintenance.go
  internal/controller/repository_maintenance_test.go
  internal/controller/velero.go
  internal/controller/velero_test.go
  pkg/common/common.go
Labels: approved, lgtm

#1717 Add user documentation for the node affinity and pod scheduling.
  docs/scheduling_and_node_affinity.md
Labels: approved, lgtm

#1718 fix: backport compatibility must-gather
  .gitignore
  must-gather/Dockerfile
  must-gather/README.md
  must-gather/deprecated/gather_1h
  must-gather/deprecated/gather_1h_essential
  must-gather/deprecated/gather_24h
  must-gather/deprecated/gather_24h_essential
  must-gather/deprecated/gather_6h
  must-gather/deprecated/gather_6h_essential
  must-gather/deprecated/gather_72h
  must-gather/deprecated/gather_72h_essential
  must-gather/deprecated/gather_all
  must-gather/deprecated/gather_all_essential
  must-gather/deprecated/gather_metrics_dump
  must-gather/deprecated/gather_with_timeout
  must-gather/deprecated/gather_without_tls
  must-gather/pkg/cli.go
Labels: approved

#1722 OADP-5960: Don't mount default creds if no BSLs or VSLs for provider
  internal/controller/nodeagent.go
  internal/controller/nodeagent_test.go
  internal/controller/validator.go
  internal/controller/velero.go
  internal/controller/velero_test.go
  pkg/credentials/credentials.go
Labels: approved, lgtm, jira/valid-reference

#1684 OADP-5782: Add hypershift-oadp-plugin E2E tests
  Makefile
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/samples/oadp_v1alpha1_dataprotectionapplication.yaml
  go.mod
  go.sum
  tests/e2e/e2e_suite_test.go
  tests/e2e/hcp_backup_restore_suite_test.go
  tests/e2e/lib/apps.go
  tests/e2e/lib/backup.go
  tests/e2e/lib/hcp/dpa.go
  tests/e2e/lib/hcp/dpa_test.go
  tests/e2e/lib/hcp/hcp.go
  tests/e2e/lib/hcp/hcp_test.go
  tests/e2e/lib/hcp/mce.go
  tests/e2e/lib/hcp/mce_test.go
  tests/e2e/lib/hcp/types.go
  tests/e2e/lib/hcp/utils.go
  tests/e2e/lib/hcp/utils_test.go
  tests/e2e/lib/scheme.go
  tests/e2e/sample-applications/hostedcontrolplanes/hypershift/hostedcluster-agent-capi-role.yaml
  tests/e2e/sample-applications/hostedcontrolplanes/hypershift/hostedcluster-agent.yaml
  tests/e2e/sample-applications/hostedcontrolplanes/hypershift/hostedcluster-etcd-enc-key.yaml
  tests/e2e/sample-applications/hostedcontrolplanes/hypershift/hostedcluster-none.yaml
  tests/e2e/sample-applications/hostedcontrolplanes/hypershift/hostedcluster-pull-secret.yaml
  tests/e2e/sample-applications/hostedcontrolplanes/mce/mce-operand.yaml
Labels: approved, lgtm, jira/valid-reference

#1714 OADP-5901: DataProtectionTest CRD and Controller Implementation
  PROJECT
  api/v1alpha1/dataprotectiontest_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  bundle/manifests/oadp.openshift.io_dataprotectiontests.yaml
  bundle/manifests/openshift-adp-dataprotectiontest-editor-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/openshift-adp-dataprotectiontest-viewer-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  cmd/main.go
  config/crd/bases/oadp.openshift.io_dataprotectiontests.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/oadp-operator.clusterserviceversion.yaml
  config/rbac/dataprotectiontest_editor_role.yaml
  config/rbac/dataprotectiontest_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/oadp_v1alpha1_dataprotectiontest.yaml
  go.mod
  go.sum
  internal/controller/dataprotectiontest_controller.go
  internal/controller/dataprotectiontest_controller_test.go
  internal/controller/suite_test.go
  pkg/cloudprovider/aws.go
  pkg/cloudprovider/interface.go
  pkg/utils/credentials.go
  pkg/utils/parse.go
  pkg/utils/parse_test.go
Labels: approved, lgtm, jira/valid-reference

#1726 fix: must-gather standards
  must-gather/README.md
  must-gather/pkg/cli.go
  must-gather/pkg/templates/summary.go
Labels: approved, lgtm

#1729 [oadp-1.5] OADP-5782: Add hypershift-oadp-plugin as a default one in oadp-operator + E2E
  Makefile
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/samples/oadp_v1alpha1_dataprotectionapplication.yaml
  go.mod
  go.sum
  internal/controller/velero_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/hcp_backup_restore_suite_test.go
  tests/e2e/lib/apps.go
  tests/e2e/lib/backup.go
  tests/e2e/lib/hcp/dpa.go
  tests/e2e/lib/hcp/dpa_test.go
  tests/e2e/lib/hcp/hcp.go
  tests/e2e/lib/hcp/hcp_test.go
  tests/e2e/lib/hcp/mce.go
  tests/e2e/lib/hcp/mce_test.go
  tests/e2e/lib/hcp/types.go
  tests/e2e/lib/hcp/utils.go
  tests/e2e/lib/hcp/utils_test.go
  tests/e2e/lib/scheme.go
  tests/e2e/sample-applications/hostedcontrolplanes/hypershift/hostedcluster-agent-capi-role.yaml
  tests/e2e/sample-applications/hostedcontrolplanes/hypershift/hostedcluster-agent.yaml
  tests/e2e/sample-applications/hostedcontrolplanes/hypershift/hostedcluster-etcd-enc-key.yaml
  tests/e2e/sample-applications/hostedcontrolplanes/hypershift/hostedcluster-none.yaml
  tests/e2e/sample-applications/hostedcontrolplanes/hypershift/hostedcluster-pull-secret.yaml
  tests/e2e/sample-applications/hostedcontrolplanes/mce/mce-operand.yaml
Labels: approved, lgtm, jira/valid-reference

#1723 fix: must-gather e2e test
  .gitignore
  Makefile
  must-gather/README.md
  must-gather/pkg/cli.go
  must-gather/pkg/templates/summary.go
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/lib/apps.go
  tests/e2e/lib/scheme.go
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm

#1731 OADP-6019: Add emptyDir volume for tmp files to avoid readonly root filesystem issues.
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  pkg/bucket/client.go
Labels: approved, lgtm, jira/valid-reference

#1734 OADP-5904: [oadp-1.4] fix: must-gather backport for 1.4
  .gitignore
  Makefile
  must-gather/Dockerfile
  must-gather/Makefile
  must-gather/README.md
  must-gather/cmd/main.go
  must-gather/collection-scripts/_metrics_chart_template_part_1.html
  must-gather/collection-scripts/_metrics_chart_template_part_2.html
  must-gather/collection-scripts/debug/tail_failed_pods
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_crds
  must-gather/collection-scripts/gather_crs
  must-gather/collection-scripts/gather_logs
  must-gather/collection-scripts/gather_logs_without_zip
  must-gather/collection-scripts/gather_metrics
  must-gather/collection-scripts/gather_metrics_dump
  must-gather/collection-scripts/gather_versions
  must-gather/collection-scripts/gather_without_tls
  must-gather/collection-scripts/logs/gather_logs_backup
  must-gather/collection-scripts/logs/gather_logs_pods
  must-gather/collection-scripts/logs/gather_logs_pvb
  must-gather/collection-scripts/logs/gather_logs_pvr
  must-gather/collection-scripts/logs/gather_logs_restore
  must-gather/collection-scripts/pwait
  must-gather/collection-scripts/time_window_gather/gather_1h
  must-gather/collection-scripts/time_window_gather/gather_1h_essential
  must-gather/collection-scripts/time_window_gather/gather_24h
  must-gather/collection-scripts/time_window_gather/gather_24h_essential
  must-gather/collection-scripts/time_window_gather/gather_6h
  must-gather/collection-scripts/time_window_gather/gather_6h_essential
  must-gather/collection-scripts/time_window_gather/gather_72h
  must-gather/collection-scripts/time_window_gather/gather_72h_essential
  must-gather/collection-scripts/time_window_gather/gather_all
  must-gather/collection-scripts/time_window_gather/gather_all_essential
  must-gather/collection-scripts/time_window_gather/gather_with_timeout
  must-gather/deprecated/gather_1h
  must-gather/deprecated/gather_1h_essential
  must-gather/deprecated/gather_24h
  must-gather/deprecated/gather_24h_essential
  must-gather/deprecated/gather_6h
  must-gather/deprecated/gather_6h_essential
  must-gather/deprecated/gather_72h
  must-gather/deprecated/gather_72h_essential
  must-gather/deprecated/gather_all
  must-gather/deprecated/gather_all_essential
  must-gather/deprecated/gather_metrics_dump
  must-gather/deprecated/gather_with_timeout
  must-gather/deprecated/gather_without_tls
  must-gather/go.mod
  must-gather/go.sum
  must-gather/pkg/cli.go
  must-gather/pkg/gather/gather.go
  must-gather/pkg/gvk/gvk.go
  must-gather/pkg/templates/summary.go
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/lib/apps.go
  tests/e2e/must-gather_suite_test.go
  tests/e2e/virt_backup_restore_suite_test.go
Labels: approved, lgtm, jira/valid-reference

#1736 [oadp-1.5] OADP-6005: Set pinned version for hypershift-oadp-plugin on oadp-1.5
  bundle/manifests/oadp-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  pkg/common/common.go
  pkg/credentials/credentials_test.go
  tests/e2e/lib/hcp/dpa.go
  tests/e2e/lib/hcp/dpa_test.go
Labels: approved, lgtm, jira/valid-reference

#1737 [oadp-1.3] OADP-5905: must-gather backport for 1.3
  .gitignore
  Makefile
  must-gather/Dockerfile
  must-gather/Makefile
  must-gather/README.md
  must-gather/cmd/main.go
  must-gather/collection-scripts/_metrics_chart_template_part_1.html
  must-gather/collection-scripts/_metrics_chart_template_part_2.html
  must-gather/collection-scripts/debug/tail_failed_pods
  must-gather/collection-scripts/gather
  must-gather/collection-scripts/gather_crds
  must-gather/collection-scripts/gather_crs
  must-gather/collection-scripts/gather_logs
  must-gather/collection-scripts/gather_logs_without_zip
  must-gather/collection-scripts/gather_metrics
  must-gather/collection-scripts/gather_metrics_dump
  must-gather/collection-scripts/gather_versions
  must-gather/collection-scripts/gather_without_tls
  must-gather/collection-scripts/logs/gather_logs_backup
  must-gather/collection-scripts/logs/gather_logs_pods
  must-gather/collection-scripts/logs/gather_logs_pvb
  must-gather/collection-scripts/logs/gather_logs_pvr
  must-gather/collection-scripts/logs/gather_logs_restore
  must-gather/collection-scripts/pwait
  must-gather/collection-scripts/time_window_gather/gather_1h
  must-gather/collection-scripts/time_window_gather/gather_1h_essential
  must-gather/collection-scripts/time_window_gather/gather_24h
  must-gather/collection-scripts/time_window_gather/gather_24h_essential
  must-gather/collection-scripts/time_window_gather/gather_6h
  must-gather/collection-scripts/time_window_gather/gather_6h_essential
  must-gather/collection-scripts/time_window_gather/gather_72h
  must-gather/collection-scripts/time_window_gather/gather_72h_essential
  must-gather/collection-scripts/time_window_gather/gather_all
  must-gather/collection-scripts/time_window_gather/gather_all_essential
  must-gather/collection-scripts/time_window_gather/gather_with_timeout
  must-gather/deprecated/gather_1h
  must-gather/deprecated/gather_1h_essential
  must-gather/deprecated/gather_24h
  must-gather/deprecated/gather_24h_essential
  must-gather/deprecated/gather_6h
  must-gather/deprecated/gather_6h_essential
  must-gather/deprecated/gather_72h
  must-gather/deprecated/gather_72h_essential
  must-gather/deprecated/gather_all
  must-gather/deprecated/gather_all_essential
  must-gather/deprecated/gather_metrics_dump
  must-gather/deprecated/gather_with_timeout
  must-gather/deprecated/gather_without_tls
  must-gather/go.mod
  must-gather/go.sum
  must-gather/pkg/cli.go
  must-gather/pkg/gather/gather.go
  must-gather/pkg/gvk/gvk.go
  must-gather/pkg/templates/summary.go
  tests/e2e/backup_restore_suite_test.go
  tests/e2e/dpa_deployment_suite_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/lib/apps.go
  tests/e2e/lib/dpa_helpers.go
  tests/e2e/must-gather_suite_test.go
Labels: approved, lgtm, jira/valid-reference

#1703 fix: upgrade template
  Makefile
  build/Dockerfile.bundle
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
  tests/e2e/upgrade_suite_test.go
Labels: approved, lgtm
